module.exports = {
  maths: {
    algebra: [
      { q: "Solve: 3x + 7 = 22", options: ["x = 3", "x = 5", "x = 7", "x = 4"], answer: 1, difficulty: 1 },
      { q: "Expand: 2(x + 4)", options: ["2x + 4", "2x + 8", "x + 8", "2x + 6"], answer: 1, difficulty: 1 },
      { q: "Solve: 5x - 3 = 2x + 9", options: ["x = 2", "x = 4", "x = 6", "x = 3"], answer: 1, difficulty: 2 },
      { q: "Factorise: x\u00b2 + 5x + 6", options: ["(x+1)(x+6)", "(x+2)(x+3)", "(x+3)(x+3)", "(x+1)(x+5)"], answer: 1, difficulty: 2 },
      { q: "Simplify: 3a + 2b - a + 4b", options: ["2a + 6b", "4a + 6b", "2a + 2b", "3a + 6b"], answer: 0, difficulty: 1 },
      { q: "Solve: 2(x - 3) = x + 4", options: ["x = 10", "x = 7", "x = 5", "x = 8"], answer: 0, difficulty: 2 },
      { q: "What is the value of x if x/4 + 3 = 7?", options: ["12", "16", "20", "8"], answer: 1, difficulty: 1 },
      { q: "Expand and simplify: (x + 3)(x + 2)", options: ["x\u00b2 + 5x + 6", "x\u00b2 + 6x + 5", "x\u00b2 + 5x + 5", "x\u00b2 + 6x + 6"], answer: 0, difficulty: 2 },
      { q: "Simplify 7y - 3y + 2y", options: ["6y", "8y", "5y", "12y"], answer: 0, difficulty: 1 },
      { q: "Solve 4x - 9 = 15", options: ["x = 4", "x = 5", "x = 6", "x = 7"], answer: 2, difficulty: 1 },
      { q: "Expand 3(x + 4)", options: ["3x + 4", "3x + 7", "3x + 12", "x + 12"], answer: 2, difficulty: 1 },
      { q: "Factorise 6x + 9", options: ["3(2x + 3)", "6(x + 9)", "3(2x + 9)", "9(x + 1)"], answer: 0, difficulty: 1 },
      { q: "If y = 2x - 1, what is y when x = 5?", options: ["8", "9", "10", "11"], answer: 1, difficulty: 1 },
      { q: "Solve 5x + 3 = 2x + 18", options: ["x = 3", "x = 4", "x = 5", "x = 6"], answer: 2, difficulty: 2 },
      { q: "Expand and simplify (x + 3)(x + 2)", options: ["x\u00b2 + 5x + 6", "x\u00b2 + 6", "2x + 5", "x\u00b2 + 5x + 5"], answer: 0, difficulty: 2 },
    ],
    bearings: [
      { q: "A bearing is always measured from which direction?", options: ["South", "East", "North", "West"], answer: 2, difficulty: 1 },
      { q: "Bearings are measured in which direction?", options: ["Anticlockwise", "Clockwise", "Both ways", "Depends on question"], answer: 1, difficulty: 1 },
      { q: "What is the bearing of East?", options: ["000\u00b0", "090\u00b0", "180\u00b0", "270\u00b0"], answer: 1, difficulty: 1 },
      { q: "What is the bearing of South-West?", options: ["135\u00b0", "225\u00b0", "315\u00b0", "045\u00b0"], answer: 1, difficulty: 1 },
      { q: "If the bearing of B from A is 070\u00b0, what is the bearing of A from B?", options: ["250\u00b0", "110\u00b0", "290\u00b0", "070\u00b0"], answer: 0, difficulty: 2 },
      { q: "A ship sails on a bearing of 135\u00b0. Which direction is it heading?", options: ["North-East", "South-East", "South-West", "North-West"], answer: 1, difficulty: 1 },
      { q: "The bearing of X from Y is 300\u00b0. What is the bearing of Y from X?", options: ["120\u00b0", "060\u00b0", "240\u00b0", "300\u00b0"], answer: 0, difficulty: 2 },
      { q: "A bearing must always be written as:", options: ["1 digit", "2 digits", "3 digits", "4 digits"], answer: 2, difficulty: 1 },
      { q: "What is the bearing of North?", options: ["360\u00b0", "000\u00b0", "090\u00b0", "180\u00b0"], answer: 1, difficulty: 1 },
      { q: "If bearing of P from Q is 045\u00b0, P is in which direction from Q?", options: ["North-East", "South-East", "North-West", "South-West"], answer: 0, difficulty: 2 },
    ],
    compound_shapes: [
      { q: "A compound shape is made of a 6\u00d74 rectangle and a 3\u00d74 rectangle. Total area?", options: ["36 cm\u00b2", "30 cm\u00b2", "24 cm\u00b2", "42 cm\u00b2"], answer: 0, difficulty: 1 },
      { q: "An L-shape has outer dimensions 10\u00d78 with a 4\u00d73 piece cut out. Area?", options: ["68 cm\u00b2", "80 cm\u00b2", "76 cm\u00b2", "56 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "A T-shape is made of two rectangles: 8\u00d72 on top and 3\u00d76 below. Total area?", options: ["34 cm\u00b2", "30 cm\u00b2", "36 cm\u00b2", "28 cm\u00b2"], answer: 0, difficulty: 1 },
      { q: "To find perimeter of a compound shape, you:", options: ["Add all inner sides", "Add all outer sides", "Multiply length \u00d7 width", "Add areas together"], answer: 1, difficulty: 1 },
      { q: "A rectangle 12\u00d75 has a 4\u00d73 rectangle removed from corner. Perimeter?", options: ["34 cm", "48 cm", "40 cm", "44 cm"], answer: 2, difficulty: 2 },
      { q: "Two squares of side 5cm overlap by 2cm. Combined area (no overlap counted twice)?", options: ["46 cm\u00b2", "50 cm\u00b2", "48 cm\u00b2", "44 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "A shape is a 10\u00d76 rectangle with a semicircle (diameter 6) on one end. Area? (\u03c0=3.14)", options: ["74.13 cm\u00b2", "60 cm\u00b2", "88.26 cm\u00b2", "81.42 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "Compound shape: rectangle 8\u00d75 joined to triangle base 8, height 3. Total area?", options: ["52 cm\u00b2", "55 cm\u00b2", "64 cm\u00b2", "40 cm\u00b2"], answer: 0, difficulty: 1 },
    ],
    circles: [
      { q: "What is the circumference of a circle with radius 7cm? (\u03c0 = 22/7)", options: ["44 cm", "22 cm", "154 cm", "38 cm"], answer: 0, difficulty: 1 },
      { q: "Find the area of a circle with radius 5cm (\u03c0 = 3.14)", options: ["78.5 cm\u00b2", "31.4 cm\u00b2", "15.7 cm\u00b2", "25 cm\u00b2"], answer: 0, difficulty: 1 },
      { q: "Diameter of a circle is 12cm. What is the circumference? (\u03c0 = 3.14)", options: ["37.68 cm", "18.84 cm", "113.04 cm", "75.36 cm"], answer: 0, difficulty: 1 },
      { q: "A semicircle has diameter 10cm. What is its perimeter? (\u03c0 = 3.14)", options: ["25.7 cm", "15.7 cm", "31.4 cm", "20.7 cm"], answer: 0, difficulty: 2 },
      { q: "Area of a circle is 154 cm\u00b2. What is the radius? (\u03c0 = 22/7)", options: ["7 cm", "14 cm", "49 cm", "21 cm"], answer: 0, difficulty: 2 },
      { q: "A quarter circle has radius 8cm. What is its area? (\u03c0 = 3.14)", options: ["50.24 cm\u00b2", "200.96 cm\u00b2", "25.12 cm\u00b2", "100.48 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "The formula for circumference is:", options: ["\u03c0r\u00b2", "2\u03c0r", "\u03c0d\u00b2", "2\u03c0d"], answer: 1, difficulty: 1 },
      { q: "A circle has circumference 31.4cm. What is the diameter? (\u03c0 = 3.14)", options: ["10 cm", "5 cm", "20 cm", "15 cm"], answer: 0, difficulty: 2 },
    ],
    angles: [
      { q: "What is the sum of interior angles of a triangle?", options: ["90\u00b0", "180\u00b0", "360\u00b0", "270\u00b0"], answer: 1, difficulty: 1 },
      { q: "Sum of interior angles of a hexagon (6 sides)?", options: ["540\u00b0", "720\u00b0", "900\u00b0", "360\u00b0"], answer: 1, difficulty: 1 },
      { q: "Each exterior angle of a regular pentagon?", options: ["108\u00b0", "72\u00b0", "60\u00b0", "90\u00b0"], answer: 1, difficulty: 2 },
      { q: "Exterior angles of any polygon always sum to:", options: ["180\u00b0", "360\u00b0", "540\u00b0", "720\u00b0"], answer: 1, difficulty: 1 },
      { q: "Each interior angle of a regular octagon?", options: ["135\u00b0", "120\u00b0", "140\u00b0", "150\u00b0"], answer: 0, difficulty: 2 },
      { q: "A regular polygon has exterior angle 40\u00b0. How many sides?", options: ["8", "9", "10", "12"], answer: 1, difficulty: 2 },
      { q: "Formula for sum of interior angles of n-sided polygon?", options: ["180n", "(n-2)\u00d7180", "(n+2)\u00d7180", "360\u00f7n"], answer: 1, difficulty: 1 },
      { q: "Interior + Exterior angle at any vertex equals:", options: ["90\u00b0", "180\u00b0", "360\u00b0", "270\u00b0"], answer: 1, difficulty: 1 },
      { q: "Sum of interior angles of a quadrilateral?", options: ["180\u00b0", "270\u00b0", "360\u00b0", "540\u00b0"], answer: 2, difficulty: 1 },
      { q: "A regular polygon has interior angle 150\u00b0. How many sides?", options: ["10", "12", "8", "15"], answer: 1, difficulty: 2 },
    ],
    probability: [
      { q: "A fair dice is rolled. P(getting 6)?", options: ["1/2", "1/6", "1/3", "6/6"], answer: 1, difficulty: 1 },
      { q: "A coin is flipped twice. P(two heads)?", options: ["1/2", "1/4", "1/3", "3/4"], answer: 1, difficulty: 1 },
      { q: "Bag has 3 red, 5 blue, 2 green balls. P(blue)?", options: ["1/2", "5/10", "3/10", "2/10"], answer: 1, difficulty: 1 },
      { q: "P(event) + P(not event) = ?", options: ["0", "0.5", "1", "2"], answer: 2, difficulty: 1 },
      { q: "P(impossible event) = ?", options: ["0", "1", "0.5", "-1"], answer: 0, difficulty: 1 },
      { q: "A spinner has sections: 2 red, 3 blue, 5 green. P(not green)?", options: ["1/2", "5/10", "3/10", "7/10"], answer: 0, difficulty: 2 },
      { q: "Two dice rolled. P(total = 7)?", options: ["1/6", "6/36", "7/36", "1/12"], answer: 1, difficulty: 2 },
      { q: "A card is drawn from 52 cards. P(heart)?", options: ["1/4", "1/13", "1/52", "1/2"], answer: 0, difficulty: 1 },
      { q: "Events A and B are independent. P(A)=0.3, P(B)=0.5. P(A and B)?", options: ["0.8", "0.15", "0.2", "0.35"], answer: 1, difficulty: 2 },
      { q: "Relative frequency of heads in 200 flips is 0.55. How many heads?", options: ["110", "100", "55", "90"], answer: 0, difficulty: 2 },
      { q: "You flip a coin twice. Probability of getting 2 heads?", options: ["1/4", "1/2", "3/4", "1"], answer: 0, difficulty: 1 },
      { q: "A bag has 4 red, 3 green, 3 blue counters. P(red or blue)?", options: ["4/10", "7/10", "3/10", "1/2"], answer: 1, difficulty: 2 },
      { q: "Probability an event will NOT happen is 0.3. Probability it WILL happen?", options: ["0.3", "0.7", "1.3", "0"], answer: 1, difficulty: 1 },
      { q: "A spinner has 4 equal sections: red, blue, green, yellow. P(not red)?", options: ["1/4", "1/2", "3/4", "1"], answer: 2, difficulty: 1 },
    ],
    percentages: [
      { q: "What is 25% of 160?", options: ["40", "35", "45", "32"], answer: 0, difficulty: 1 },
      { q: "A shirt costs \u00a340. Sale is 15% off. Sale price?", options: ["\u00a334", "\u00a336", "\u00a332", "\u00a338"], answer: 0, difficulty: 1 },
      { q: "Express 45 out of 60 as a percentage", options: ["70%", "75%", "80%", "65%"], answer: 1, difficulty: 1 },
      { q: "A price increases from \u00a380 to \u00a3100. % increase?", options: ["20%", "25%", "15%", "30%"], answer: 1, difficulty: 2 },
      { q: "After 10% decrease, value is 63. Original value?", options: ["70", "73", "67", "60"], answer: 0, difficulty: 2 },
      { q: "VAT is 20%. Item costs \u00a360 before VAT. Total?", options: ["\u00a372", "\u00a368", "\u00a380", "\u00a370"], answer: 0, difficulty: 1 },
      { q: "A house was \u00a3200,000. Increased by 5% then decreased by 5%. Final price?", options: ["\u00a3200,000", "\u00a3199,500", "\u00a3199,000", "\u00a3201,000"], answer: 1, difficulty: 2 },
      { q: "30% of a number is 45. What is the number?", options: ["135", "150", "120", "180"], answer: 1, difficulty: 2 },
      { q: "\u00a3500 invested at 3% simple interest for 4 years. Total interest?", options: ["\u00a360", "\u00a350", "\u00a345", "\u00a365"], answer: 0, difficulty: 1 },
      { q: "Population grows from 5000 to 6500. % increase?", options: ["25%", "30%", "35%", "20%"], answer: 1, difficulty: 2 },
      { q: "Write 45% as a fraction in simplest form", options: ["9/20", "45/100", "4/5", "9/10"], answer: 0, difficulty: 1 },
    ],
    fractions: [
      { q: "Work out 3/5 - 1/4", options: ["2/1", "7/20", "1/2", "4/9"], answer: 1, difficulty: 2 },
      { q: "What is 0.6 \u00d7 0.4?", options: ["2.4", "0.24", "0.024", "24"], answer: 1, difficulty: 1 },
    ],
    ratio: [
      { q: "The ratio of boys to girls is 2:3. If there are 10 boys, how many girls?", options: ["12", "15", "18", "20"], answer: 1, difficulty: 1 },
      { q: "5 tickets cost \u00a335. How much do 8 tickets cost?", options: ["\u00a348", "\u00a356", "\u00a360", "\u00a364"], answer: 1, difficulty: 1 },
    ],
    pythagoras: [
      { q: "Right-angled triangle: sides 5cm, 12cm. Hypotenuse = ?", options: ["13cm", "15cm", "17cm", "7cm"], answer: 0, difficulty: 2 },
      { q: "Right-angled triangle: hypotenuse = 10cm, one side = 6cm. Other side = ?", options: ["4cm", "8cm", "12cm", "16cm"], answer: 1, difficulty: 2 },
      { q: "Is a triangle with sides 9, 12, 15 right-angled?", options: ["Yes", "No", "Cannot tell", "Only if equilateral"], answer: 0, difficulty: 2 },
      { q: "A right-angled triangle has short sides 6cm and 8cm. Length of hypotenuse?", options: ["9cm", "10cm", "12cm", "14cm"], answer: 1, difficulty: 1 },
    ],
    sequences: [
      { q: "Next term in 3, 6, 12, 24, ...", options: ["36", "42", "48", "50"], answer: 2, difficulty: 1 },
      { q: "What is 3\u2074?", options: ["12", "27", "64", "81"], answer: 3, difficulty: 1 },
      { q: "Simplify 2\u00b3 \u00d7 2\u00b2", options: ["2\u2075", "2\u2076", "4\u2075", "2\u00b9"], answer: 0, difficulty: 2 },
      { q: "Write 36000 in standard form", options: ["36 \u00d7 10\u00b3", "3.6 \u00d7 10\u2074", "0.36 \u00d7 10\u2075", "3.6 \u00d7 10\u00b3"], answer: 1, difficulty: 2 },
    ],
    units: [
      { q: "Convert 2.5 km to metres", options: ["25 m", "250 m", "2500 m", "25000 m"], answer: 2, difficulty: 1 },
      { q: "How many minutes in 3.5 hours?", options: ["180", "200", "210", "350"], answer: 2, difficulty: 1 },
      { q: "Volume of a cuboid 3cm \u00d7 4cm \u00d7 5cm", options: ["12 cm\u00b3", "35 cm\u00b3", "60 cm\u00b3", "120 cm\u00b3"], answer: 2, difficulty: 1 },
    ],
    statistics: [
      { q: "Find the median of: 3, 7, 2, 9, 5", options: ["2", "5", "7", "9"], answer: 1, difficulty: 1 },
      { q: "Range of: 12, 5, 19, 8, 15", options: ["7", "12", "14", "19"], answer: 2, difficulty: 1 },
      { q: "In a class of 30: 18 like Maths, 12 like Science, 5 like both. How many like neither?", options: ["0", "5", "7", "25"], answer: 1, difficulty: 2 },
    ],
    rounding: [
      { q: "Round 6.382 to 2 decimal places", options: ["6.38", "6.39", "6.40", "6.3"], answer: 0, difficulty: 1 },
      { q: "Round 3.456 to 1 decimal place", options: ["3.4", "3.5", "3.46", "3.0"], answer: 1, difficulty: 1 },
      { q: "Round 0.0678 to 2 significant figures", options: ["0.07", "0.068", "0.067", "0.06"], answer: 1, difficulty: 2 },
      { q: "Round 2450 to 1 significant figure", options: ["2000", "2500", "3000", "2400"], answer: 1, difficulty: 2 },
      { q: "Truncate 7.89 to 1 decimal place", options: ["7.8", "7.9", "8.0", "7.0"], answer: 0, difficulty: 2 },
    ],
    compound_interest: [
      { q: "\u00a31000 invested at 5% for 2 years compound interest. Amount after 2 years?", options: ["\u00a31050", "\u00a31100", "\u00a31102.50", "\u00a31200"], answer: 2, difficulty: 2 },
      { q: "\u00a3500 at 10% compound interest for 2 years. Final amount?", options: ["\u00a3600", "\u00a3605", "\u00a3610", "\u00a3550"], answer: 1, difficulty: 2 },
      { q: "A car loses 20% of its value each year. Worth \u00a310000 now. Value after 2 years?", options: ["\u00a36000", "\u00a36400", "\u00a38000", "\u00a37200"], answer: 1, difficulty: 2 },
    ],
    loci: [
      { q: "The set of all points the same distance from a fixed point is:", options: ["A straight line", "A circle", "A square", "An angle bisector"], answer: 1, difficulty: 1 },
      { q: "The locus of points equidistant from two fixed points is:", options: ["A circle", "A perpendicular bisector", "An arc", "A parallel line"], answer: 1, difficulty: 2 },
    ],
    inequalities: [
      { q: "Solve: 3x + 2 > 11", options: ["x > 3", "x > 4", "x > 5", "x > 2"], answer: 0, difficulty: 1 },
      { q: "Which integer satisfies -2 < x \u2264 3?", options: ["-2", "4", "3", "-3"], answer: 2, difficulty: 1 },
      { q: "Solve: 2x - 5 < 9", options: ["x < 7", "x < 2", "x < 8", "x < 6"], answer: 0, difficulty: 1 },
      { q: "List integers satisfying -1 \u2264 n < 4", options: ["-1,0,1,2,3", "0,1,2,3,4", "-1,0,1,2,3,4", "0,1,2,3"], answer: 0, difficulty: 2 },
    ],
    transformations: [
      { q: "A shape is reflected in the y-axis. Point (3,2) becomes:", options: ["(-3,2)", "(3,-2)", "(-3,-2)", "(2,3)"], answer: 0, difficulty: 1 },
      { q: "A shape is rotated 90\u00b0 clockwise about the origin. Point (2,3) becomes:", options: ["(3,-2)", "(-3,2)", "(-2,-3)", "(3,2)"], answer: 0, difficulty: 2 },
      { q: "A translation of (3,-2) means move:", options: ["3 left, 2 up", "3 right, 2 down", "3 right, 2 up", "3 left, 2 down"], answer: 1, difficulty: 1 },
      { q: "Enlargement scale factor 2 from centre O. A point 3cm from O becomes:", options: ["1.5cm from O", "5cm from O", "6cm from O", "9cm from O"], answer: 2, difficulty: 1 },
      { q: "Which transformation changes the size of a shape?", options: ["Reflection", "Rotation", "Translation", "Enlargement"], answer: 3, difficulty: 1 },
    ],
    direct_proportion: [
      { q: "y is directly proportional to x. When x=4, y=12. Find y when x=7", options: ["15", "21", "28", "18"], answer: 1, difficulty: 2 },
      { q: "If 3 kg of apples cost \u00a34.50, how much do 5 kg cost?", options: ["\u00a36.50", "\u00a37.00", "\u00a37.50", "\u00a38.00"], answer: 2, difficulty: 1 },
      { q: "A recipe for 4 people needs 200g flour. How much for 6 people?", options: ["250g", "300g", "350g", "400g"], answer: 1, difficulty: 1 },
    ],
    speed_distance_time: [
      { q: "A car travels 120 miles in 2 hours. Average speed?", options: ["50 mph", "60 mph", "70 mph", "80 mph"], answer: 1, difficulty: 1 },
      { q: "Speed = 30 m/s, time = 20s. Distance?", options: ["600m", "50m", "1.5m", "10m"], answer: 0, difficulty: 1 },
      { q: "Distance = 150km, speed = 50km/h. Time?", options: ["2 hours", "2.5 hours", "3 hours", "3.5 hours"], answer: 2, difficulty: 1 },
      { q: "A train travels 90km in 45 minutes. Speed in km/h?", options: ["90", "120", "135", "180"], answer: 1, difficulty: 2 },
    ],
    area_and_volume: [
      { q: "Area of a triangle: base=10cm, height=6cm", options: ["60 cm\u00b2", "30 cm\u00b2", "16 cm\u00b2", "36 cm\u00b2"], answer: 1, difficulty: 1 },
      { q: "Area of a trapezium: parallel sides 5cm and 9cm, height 4cm", options: ["28 cm\u00b2", "56 cm\u00b2", "36 cm\u00b2", "20 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "Volume of a cylinder: radius 3cm, height 7cm (\u03c0=3.14)", options: ["197.82 cm\u00b3", "65.94 cm\u00b3", "131.88 cm\u00b3", "263.76 cm\u00b3"], answer: 0, difficulty: 2 },
      { q: "Surface area of a cube with side 4cm", options: ["64 cm\u00b2", "96 cm\u00b2", "24 cm\u00b2", "48 cm\u00b2"], answer: 1, difficulty: 1 },
      { q: "Area of a parallelogram: base 8cm, perpendicular height 5cm", options: ["13 cm\u00b2", "40 cm\u00b2", "20 cm\u00b2", "80 cm\u00b2"], answer: 1, difficulty: 1 },
    ],
    simultaneous_equations: [
      { q: "Solve: x + y = 7, x - y = 3. What is x?", options: ["4", "5", "3", "6"], answer: 1, difficulty: 2 },
      { q: "Solve: 2x + y = 10, x + y = 7. What is x?", options: ["2", "3", "4", "5"], answer: 1, difficulty: 2 },
      { q: "Solve: x + y = 7, x - y = 3. What is y?", options: ["1", "2", "3", "4"], answer: 1, difficulty: 2 },
    ],
    linear_graphs: [
      { q: "What is the gradient of y = 3x + 2?", options: ["2", "3", "5", "6"], answer: 1, difficulty: 1 },
      { q: "What is the y-intercept of y = 4x - 7?", options: ["4", "-7", "7", "-4"], answer: 1, difficulty: 1 },
      { q: "A horizontal line has gradient:", options: ["1", "Undefined", "0", "Infinity"], answer: 2, difficulty: 1 },
      { q: "Two lines are parallel. They have:", options: ["Same gradient", "Same y-intercept", "Perpendicular gradients", "Same x-intercept"], answer: 0, difficulty: 1 },
      { q: "What is the equation of a line with gradient 2, passing through (0,5)?", options: ["y = 5x + 2", "y = 2x + 5", "y = 2x - 5", "y = 5x - 2"], answer: 1, difficulty: 2 },
    ],
    surds: [
      { q: "Simplify \u221a50", options: ["5\u221a2", "2\u221a5", "25\u221a2", "10\u221a5"], answer: 0, difficulty: 2 },
      { q: "Simplify \u221a18", options: ["2\u221a9", "3\u221a2", "9\u221a2", "6\u221a3"], answer: 1, difficulty: 2 },
      { q: "\u221a3 \u00d7 \u221a3 = ?", options: ["9", "3", "\u221a9", "6"], answer: 1, difficulty: 1 },
    ],
  },
  science: {
    forces: [
      { q: "What is the unit of force?", options: ["Joule", "Newton", "Watt", "Pascal"], answer: 1, difficulty: 1 },
      { q: "A 10kg object has weight (g=10 m/s\u00b2):", options: ["10N", "100N", "1000N", "1N"], answer: 1, difficulty: 1 },
      { q: "Which force slows down a moving car?", options: ["Gravity", "Friction", "Thrust", "Upthrust"], answer: 1, difficulty: 1 },
      { q: "F = ma. Force=20N, mass=5kg. Acceleration=?", options: ["100 m/s\u00b2", "4 m/s\u00b2", "25 m/s\u00b2", "15 m/s\u00b2"], answer: 1, difficulty: 1 },
      { q: "An object at rest stays at rest unless a force acts. This is Newton's:", options: ["1st Law", "2nd Law", "3rd Law", "Law of Gravity"], answer: 0, difficulty: 1 },
      { q: "A 2kg ball accelerates at 3 m/s\u00b2. Force applied?", options: ["5N", "6N", "1.5N", "8N"], answer: 1, difficulty: 2 },
      { q: "What happens to friction when surfaces are smoother?", options: ["Increases", "Decreases", "Stays same", "Becomes zero"], answer: 1, difficulty: 1 },
      { q: "A car has driving force 500N and friction 200N. Resultant force?", options: ["700N", "300N", "200N", "500N"], answer: 1, difficulty: 2 },
      { q: "If resultant force on an object is zero, the object:", options: ["Speeds up", "Slows down", "Stays at constant velocity", "Stops immediately"], answer: 2, difficulty: 2 },
      { q: "Weight is measured in:", options: ["kg", "Newtons", "m/s\u00b2", "Joules"], answer: 1, difficulty: 1 },
    ],
    electromagnetism: [
      { q: "What is an electromagnet made of?", options: ["Permanent magnet", "Coil of wire + iron core", "Copper only", "Rubber and wire"], answer: 1, difficulty: 1 },
      { q: "How can you make an electromagnet stronger?", options: ["More coils", "More current", "Add iron core", "All of these"], answer: 3, difficulty: 1 },
      { q: "What device uses an electromagnet to switch a circuit on/off?", options: ["Resistor", "Relay", "Capacitor", "Diode"], answer: 1, difficulty: 2 },
      { q: "A current-carrying wire in a magnetic field experiences a:", options: ["Force", "Voltage", "Resistance", "Charge"], answer: 0, difficulty: 1 },
      { q: "The motor effect is used in:", options: ["Generators", "Electric motors", "Transformers", "Batteries"], answer: 1, difficulty: 1 },
      { q: "Fleming's Left Hand Rule: thumb represents:", options: ["Current", "Field", "Force (motion)", "Voltage"], answer: 2, difficulty: 2 },
      { q: "What happens when you reverse current in an electromagnet?", options: ["Nothing", "It gets weaker", "Poles reverse", "It stops working"], answer: 2, difficulty: 1 },
      { q: "Which material is best for an electromagnet core?", options: ["Copper", "Soft iron", "Steel", "Aluminium"], answer: 1, difficulty: 2 },
      { q: "An electromagnet differs from a permanent magnet because it:", options: ["Is always on", "Can be switched on/off", "Is stronger", "Has no poles"], answer: 1, difficulty: 1 },
      { q: "A solenoid is:", options: ["A type of battery", "A coil of wire", "A permanent magnet", "A circuit breaker"], answer: 1, difficulty: 1 },
    ],
    work_done: [
      { q: "The formula for work done is:", options: ["Force \u00d7 Time", "Force \u00d7 Distance", "Mass \u00d7 Velocity", "Power \u00d7 Time"], answer: 1, difficulty: 1 },
      { q: "What is the unit of work done?", options: ["Newton", "Watt", "Joule", "Pascal"], answer: 2, difficulty: 1 },
      { q: "A force of 50N moves an object 4m. Work done?", options: ["200J", "12.5J", "54J", "100J"], answer: 0, difficulty: 1 },
      { q: "If you push a wall but it doesn't move, work done is:", options: ["50J", "100J", "0J", "Depends on force"], answer: 2, difficulty: 1 },
      { q: "A crane lifts 200kg by 5m (g=10). Work done against gravity?", options: ["1000J", "10000J", "40J", "2000J"], answer: 1, difficulty: 2 },
      { q: "Work done = 600J, distance = 20m. What force was applied?", options: ["30N", "12000N", "580N", "620N"], answer: 0, difficulty: 2 },
      { q: "Power = Work done \u00f7 Time. 500J in 10s = ?", options: ["50W", "5000W", "5W", "500W"], answer: 0, difficulty: 1 },
      { q: "A person does 1500J of work in 30 seconds. Their power is:", options: ["50W", "45000W", "500W", "30W"], answer: 0, difficulty: 2 },
      { q: "If no friction, work done against friction is:", options: ["Maximum", "Zero", "Infinite", "Same as gravity"], answer: 1, difficulty: 1 },
      { q: "Which scenario has the most work done? (same force)", options: ["Moving 2m", "Moving 5m", "Moving 10m", "Not moving"], answer: 2, difficulty: 1 },
    ],
    periodic_table: [
      { q: "Who created the first widely accepted periodic table?", options: ["Dalton", "Mendeleev", "Newton", "Bohr"], answer: 1, difficulty: 1 },
      { q: "Elements in the same GROUP have the same number of:", options: ["Protons", "Electron shells", "Outer electrons", "Neutrons"], answer: 2, difficulty: 1 },
      { q: "Elements in the same PERIOD have the same number of:", options: ["Outer electrons", "Electron shells", "Protons", "Neutrons"], answer: 1, difficulty: 1 },
      { q: "Group 1 elements are called:", options: ["Noble gases", "Halogens", "Alkali metals", "Transition metals"], answer: 2, difficulty: 1 },
      { q: "Group 7 elements are called:", options: ["Noble gases", "Halogens", "Alkali metals", "Alkaline earth metals"], answer: 1, difficulty: 1 },
      { q: "Group 0 elements are unreactive because they have:", options: ["No electrons", "Full outer shell", "No protons", "One outer electron"], answer: 1, difficulty: 1 },
      { q: "As you go DOWN Group 1, reactivity:", options: ["Decreases", "Increases", "Stays same", "Becomes zero"], answer: 1, difficulty: 2 },
      { q: "As you go DOWN Group 7, reactivity:", options: ["Decreases", "Increases", "Stays same", "Becomes zero"], answer: 0, difficulty: 2 },
      { q: "What is the atomic number of an element?", options: ["Number of neutrons", "Number of protons", "Mass number", "Number of shells"], answer: 1, difficulty: 1 },
      { q: "Which is a noble gas?", options: ["Sodium", "Chlorine", "Neon", "Potassium"], answer: 2, difficulty: 1 },
      { q: "Metals are found on which side of the periodic table?", options: ["Right", "Left", "Centre only", "Bottom only"], answer: 1, difficulty: 1 },
      { q: "What is the electronic structure of Sodium (atomic number 11)?", options: ["2,8,1", "2,8,2", "2,1,8", "8,2,1"], answer: 0, difficulty: 2 },
    ],
    reactions: [
      { q: "What gas is produced when acid reacts with metal?", options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], answer: 2, difficulty: 1 },
      { q: "Acid + Base \u2192 ?", options: ["Salt + Hydrogen", "Salt + Water", "Salt + CO\u2082", "Metal + Water"], answer: 1, difficulty: 1 },
      { q: "What is the pH of a neutral substance?", options: ["0", "7", "14", "1"], answer: 1, difficulty: 1 },
      { q: "Iron + Oxygen \u2192 Iron Oxide is:", options: ["Reduction", "Oxidation", "Neutralisation", "Displacement"], answer: 1, difficulty: 1 },
      { q: "Which gas turns limewater milky?", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], answer: 2, difficulty: 1 },
      { q: "In a chemical reaction, mass is:", options: ["Created", "Destroyed", "Conserved", "Doubled"], answer: 2, difficulty: 1 },
      { q: "Zinc + Copper Sulphate \u2192 Zinc Sulphate + Copper. This is:", options: ["Decomposition", "Displacement", "Neutralisation", "Combustion"], answer: 1, difficulty: 2 },
      { q: "What speeds up a reaction without being used up?", options: ["Reactant", "Product", "Catalyst", "Solvent"], answer: 2, difficulty: 2 },
      { q: "Magnesium + oxygen \u2192 ?", options: ["Magnesium oxide", "Magnesium hydroxide", "Magnesium carbonate", "Magnesium chloride"], answer: 0, difficulty: 1 },
      { q: "What pH would a strong acid have?", options: ["pH 1", "pH 7", "pH 10", "pH 14"], answer: 0, difficulty: 1 },
      { q: "Which change of state is condensation?", options: ["Solid to liquid", "Liquid to gas", "Gas to liquid", "Liquid to solid"], answer: 2, difficulty: 1 },
      { q: "Which method separates sand from water?", options: ["Evaporation", "Distillation", "Filtration", "Chromatography"], answer: 2, difficulty: 1 },
      { q: "Which is a chemical change?", options: ["Melting ice", "Dissolving salt", "Burning wood", "Boiling water"], answer: 2, difficulty: 1 },
      { q: "Which metal is most reactive?", options: ["Gold", "Iron", "Potassium", "Copper"], answer: 2, difficulty: 2 },
      { q: "Neutralisation is acid + base \u2192 ?", options: ["Acid + water", "Salt + water", "Salt + hydrogen", "Water only"], answer: 1, difficulty: 1 },
      { q: "Which gas is the main greenhouse gas linked to burning fossil fuels?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], answer: 2, difficulty: 1 },
      { q: "Crude oil is separated by:", options: ["Filtration", "Fractional distillation", "Chromatography", "Electrolysis"], answer: 1, difficulty: 2 },
      { q: "Ceramics are good thermal:", options: ["Conductors", "Insulators", "Reflectors", "Magnets"], answer: 1, difficulty: 1 },
      { q: "What is the chemical symbol for sodium?", options: ["S", "So", "Na", "N"], answer: 2, difficulty: 1 },
      { q: "What is the formula for carbon dioxide?", options: ["CO", "CO\u2082", "C\u2082O", "CaO"], answer: 1, difficulty: 1 },
      { q: "Which property is typical of metals?", options: ["Dull", "Brittle", "Poor conductor of heat", "Malleable"], answer: 3, difficulty: 1 },
      { q: "What 3 things are needed for a fire?", options: ["Fuel, oxygen, heat", "Fuel, nitrogen, light", "Fuel, carbon dioxide, heat", "Water, oxygen, heat"], answer: 0, difficulty: 1 },
      { q: "Which type of rock is formed from cooled magma or lava?", options: ["Sedimentary", "Igneous", "Metamorphic", "Fossil"], answer: 1, difficulty: 1 },
      { q: "Which gas makes up ~78% of the atmosphere?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], answer: 2, difficulty: 1 },
      { q: "Where are protons found?", options: ["Orbiting the nucleus", "In the nucleus", "In shells", "Outside the atom"], answer: 1, difficulty: 1 },
      { q: "Pure water boils at:", options: ["90\u00b0C", "100\u00b0C", "110\u00b0C", "It varies"], answer: 1, difficulty: 1 },
    ],
    biology: [
      { q: "Which part of a plant cell is NOT found in an animal cell?", options: ["Nucleus", "Cell membrane", "Cell wall", "Cytoplasm"], answer: 2, difficulty: 1 },
      { q: "Which enzyme breaks down starch in the mouth?", options: ["Protease", "Lipase", "Amylase", "Bile"], answer: 2, difficulty: 1 },
      { q: "Word equation for aerobic respiration:", options: ["Glucose + oxygen \u2192 carbon dioxide + water + energy", "Glucose \u2192 lactic acid + energy", "Carbon dioxide + water \u2192 glucose + oxygen", "Oxygen + water \u2192 glucose + energy"], answer: 0, difficulty: 2 },
      { q: "What is a producer in a food chain?", options: ["An animal that eats plants", "An organism that makes its own food using sunlight", "An animal that hunts other animals", "Bacteria that break down dead material"], answer: 1, difficulty: 1 },
      { q: "Where does fertilisation occur in humans?", options: ["Ovary", "Uterus", "Oviduct/Fallopian tube", "Vagina"], answer: 2, difficulty: 2 },
      { q: "Which organ produces bile?", options: ["Stomach", "Pancreas", "Liver", "Small intestine"], answer: 2, difficulty: 1 },
      { q: "What happens to your diaphragm when you breathe in?", options: ["Moves up and flattens", "Moves down and flattens", "Moves up and becomes dome-shaped", "Moves down and becomes dome-shaped"], answer: 1, difficulty: 2 },
      { q: "Iodine solution turns blue-black in the presence of:", options: ["Sugar", "Protein", "Starch", "Fat"], answer: 2, difficulty: 1 },
      { q: "Which is an example of inherited variation?", options: ["A scar", "Eye colour", "A tattoo", "Dyed hair"], answer: 1, difficulty: 1 },
      { q: "What do root hair cells absorb from soil?", options: ["Oxygen and glucose", "Carbon dioxide and light", "Water and minerals", "Chlorophyll"], answer: 2, difficulty: 1 },
    ],
    physics: [
      { q: "Energy cannot be created or destroyed, only transferred. This is the law of:", options: ["Conservation of mass", "Conservation of energy", "Gravity", "Motion"], answer: 1, difficulty: 1 },
      { q: "Which component is used to measure current?", options: ["Voltmeter", "Ammeter", "Resistor", "Battery"], answer: 1, difficulty: 1 },
      { q: "Light travels fastest in:", options: ["Air", "Water", "Glass", "Vacuum"], answer: 3, difficulty: 1 },
      { q: "Sound cannot travel through:", options: ["Solid", "Liquid", "Gas", "Vacuum"], answer: 3, difficulty: 1 },
      { q: "Speed = distance \u00f7 time. If you run 100m in 20s, your speed is:", options: ["2 m/s", "5 m/s", "20 m/s", "2000 m/s"], answer: 1, difficulty: 1 },
      { q: "Which metal is NOT magnetic?", options: ["Iron", "Nickel", "Copper", "Cobalt"], answer: 2, difficulty: 1 },
      { q: "How long does Earth take to orbit the Sun?", options: ["24 hours", "28 days", "1 year", "10 years"], answer: 2, difficulty: 1 },
      { q: "Which is the best thermal conductor?", options: ["Plastic", "Wood", "Metal", "Air"], answer: 2, difficulty: 1 },
      { q: "In a torch, what is the main energy transfer?", options: ["Chemical \u2192 light + thermal", "Kinetic \u2192 sound", "Electrical \u2192 kinetic", "Light \u2192 chemical"], answer: 0, difficulty: 1 },
      { q: "Density = mass \u00f7 volume. An object has mass 30g and volume 10cm\u00b3. Density = ?", options: ["0.3 g/cm\u00b3", "3 g/cm\u00b3", "30 g/cm\u00b3", "300 g/cm\u00b3"], answer: 1, difficulty: 2 },
      { q: "Pressure = force \u00f7 area. Why do snowshoes stop you sinking?", options: ["Decrease force", "Increase area", "Decrease area", "Increase force"], answer: 1, difficulty: 2 },
      { q: "What type of wave is sound?", options: ["Transverse", "Longitudinal", "Electromagnetic", "Light"], answer: 1, difficulty: 1 },
      { q: "In a series circuit, if one bulb breaks, what happens to the other bulbs?", options: ["Stay on", "Get brighter", "Go off", "Get dimmer"], answer: 2, difficulty: 1 },
      { q: "Weight = mass \u00d7 gravitational field strength. On Earth g \u2248 10 N/kg. Weight of a 5kg mass?", options: ["0.5 N", "5 N", "10 N", "50 N"], answer: 3, difficulty: 1 },
      { q: "A seesaw is balanced. This means:", options: ["Total clockwise moment = total anticlockwise moment", "All forces are zero", "Mass on both sides is equal", "It has no weight"], answer: 0, difficulty: 2 },
      { q: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], answer: 2, difficulty: 1 },
      { q: "Angle of incidence = angle of ...?", options: ["Refraction", "Diffraction", "Reflection", "Absorption"], answer: 2, difficulty: 1 },
      { q: "Unit of power is:", options: ["Joule", "Newton", "Watt", "Volt"], answer: 2, difficulty: 1 },
      { q: "Work done = force \u00d7 distance. Push with 20N for 3m, work done = ?", options: ["6 J", "23 J", "60 J", "0.15 J"], answer: 2, difficulty: 1 },
      { q: "A stretched rubber band has which energy store?", options: ["Kinetic", "Thermal", "Chemical", "Elastic potential"], answer: 3, difficulty: 1 },
      { q: "A flat horizontal line on a speed-time graph means:", options: ["Stopped", "Constant speed", "Accelerating", "Decelerating"], answer: 1, difficulty: 2 },
      { q: "Rubbing a balloon on hair charges it. This is due to transfer of:", options: ["Protons", "Neutrons", "Electrons", "Nuclei"], answer: 2, difficulty: 1 },
      { q: "When light goes from air into glass it:", options: ["Speeds up and bends away from normal", "Slows down and bends towards normal", "Stops", "Doesn't change"], answer: 1, difficulty: 2 },
      { q: "How do you make an electromagnet stronger?", options: ["Fewer coils", "Lower current", "Use plastic core", "More coils"], answer: 3, difficulty: 1 },
      { q: "Moment = force \u00d7 distance. Unit for moment:", options: ["N", "J", "Nm", "W"], answer: 2, difficulty: 1 },
    ],
  },
};
