module.exports = {
  maths: {
    multiplication_division: [
      { q: "What is 24 × 6?", options: ["124", "134", "144", "154"], answer: 2, difficulty: 1 },
      { q: "What is 35 × 8?", options: ["260", "270", "280", "290"], answer: 2, difficulty: 1 },
      { q: "What is 456 ÷ 8?", options: ["55", "56", "57", "58"], answer: 2, difficulty: 2 },
      { q: "What is 372 ÷ 6?", options: ["60", "62", "64", "66"], answer: 1, difficulty: 2 },
      { q: "What is 15 × 15?", options: ["200", "215", "225", "250"], answer: 2, difficulty: 2 },
      { q: "What is 1000 ÷ 25?", options: ["30", "40", "50", "60"], answer: 1, difficulty: 2 },
    ],
    fractions: [
      { q: "What is 1/3 + 1/6?", options: ["1/2", "2/9", "1/9", "2/6"], answer: 0, difficulty: 1 },
      { q: "What is 3/5 - 1/10?", options: ["1/2", "2/5", "1/5", "7/10"], answer: 0, difficulty: 2 },
      { q: "Convert 3/4 to a decimal", options: ["0.34", "0.75", "0.25", "0.50"], answer: 1, difficulty: 1 },
      { q: "What is 2/3 of 45?", options: ["20", "25", "30", "35"], answer: 2, difficulty: 1 },
      { q: "Which fraction is equivalent to 4/6?", options: ["2/3", "2/4", "3/4", "1/2"], answer: 0, difficulty: 1 },
      { q: "What is 1 1/4 as an improper fraction?", options: ["4/4", "5/4", "3/4", "6/4"], answer: 1, difficulty: 1 },
      { q: "What is 7/8 - 3/8?", options: ["4/8", "1/2", "4/16", "Both A and B"], answer: 3, difficulty: 2 },
      { q: "Order: 1/2, 3/8, 5/8 (smallest first)", options: ["3/8, 1/2, 5/8", "1/2, 3/8, 5/8", "5/8, 1/2, 3/8", "3/8, 5/8, 1/2"], answer: 0, difficulty: 2 },
    ],
    decimals_and_percentages: [
      { q: "What is 10% of 80?", options: ["6", "8", "10", "12"], answer: 1, difficulty: 1 },
      { q: "What is 25% of 200?", options: ["25", "40", "50", "75"], answer: 2, difficulty: 1 },
      { q: "Convert 0.4 to a percentage", options: ["4%", "40%", "0.4%", "400%"], answer: 1, difficulty: 1 },
      { q: "What is 50% of 36?", options: ["12", "16", "18", "24"], answer: 2, difficulty: 1 },
      { q: "Convert 3/10 to a decimal", options: ["0.03", "0.3", "3.0", "0.33"], answer: 1, difficulty: 1 },
      { q: "What is 0.25 as a fraction?", options: ["1/5", "1/4", "1/3", "2/5"], answer: 1, difficulty: 1 },
      { q: "What is 5% of 60?", options: ["2", "3", "5", "6"], answer: 1, difficulty: 2 },
    ],
    geometry: [
      { q: "How many degrees in a right angle?", options: ["45°", "90°", "180°", "360°"], answer: 1, difficulty: 1 },
      { q: "Angles in a triangle add up to:", options: ["90°", "180°", "270°", "360°"], answer: 1, difficulty: 1 },
      { q: "A reflex angle is:", options: ["Less than 90°", "Between 90° and 180°", "Exactly 180°", "More than 180°"], answer: 3, difficulty: 1 },
      { q: "How many lines of symmetry does a square have?", options: ["1", "2", "4", "8"], answer: 2, difficulty: 1 },
      { q: "An acute angle is:", options: ["Less than 90°", "Exactly 90°", "Between 90° and 180°", "More than 180°"], answer: 0, difficulty: 1 },
      { q: "What is the name of a 3D shape with 6 rectangular faces?", options: ["Cube", "Cuboid", "Cylinder", "Prism"], answer: 1, difficulty: 1 },
    ],
    area_and_perimeter: [
      { q: "Area of a rectangle 12cm × 8cm?", options: ["40 cm²", "96 cm²", "20 cm²", "80 cm²"], answer: 1, difficulty: 1 },
      { q: "Perimeter of a rectangle 15cm × 6cm?", options: ["21cm", "42cm", "90cm", "36cm"], answer: 1, difficulty: 1 },
      { q: "A triangle has base 10cm, height 6cm. Area?", options: ["60 cm²", "30 cm²", "16 cm²", "36 cm²"], answer: 1, difficulty: 2 },
      { q: "Area of a square with side 13cm?", options: ["52 cm²", "26 cm²", "169 cm²", "130 cm²"], answer: 2, difficulty: 1 },
      { q: "A rectangle has area 48 cm² and width 6cm. Length?", options: ["6cm", "7cm", "8cm", "9cm"], answer: 2, difficulty: 2 },
    ],
    negative_numbers: [
      { q: "What is -6 + 10?", options: ["4", "-4", "16", "-16"], answer: 0, difficulty: 1 },
      { q: "What is -3 - 4?", options: ["-7", "7", "-1", "1"], answer: 0, difficulty: 1 },
      { q: "Which is smallest: -8, -2, 1, -5?", options: ["-2", "-5", "-8", "1"], answer: 2, difficulty: 1 },
      { q: "Temperature is -4°C. Rises by 9°C. New temperature?", options: ["5°C", "13°C", "-13°C", "4°C"], answer: 0, difficulty: 2 },
      { q: "What is -2 × 3?", options: ["6", "-6", "1", "-1"], answer: 1, difficulty: 2 },
    ],
    prime_numbers: [
      { q: "Which is a prime number?", options: ["4", "9", "11", "15"], answer: 2, difficulty: 1 },
      { q: "Which is NOT a prime number?", options: ["2", "7", "9", "13"], answer: 2, difficulty: 1 },
      { q: "What are the prime factors of 12?", options: ["2 and 3", "1 and 12", "4 and 3", "6 and 2"], answer: 0, difficulty: 2 },
      { q: "Is 1 a prime number?", options: ["Yes", "No"], answer: 1, difficulty: 1 },
      { q: "What is the smallest prime number?", options: ["0", "1", "2", "3"], answer: 2, difficulty: 1 },
      { q: "How many prime numbers between 1 and 10?", options: ["3", "4", "5", "6"], answer: 1, difficulty: 2 },
    ],
    roman_numerals: [
      { q: "What is XIV in numbers?", options: ["16", "14", "11", "15"], answer: 1, difficulty: 1 },
      { q: "What is 29 in Roman numerals?", options: ["XXIV", "XXIX", "XXXI", "XXVIII"], answer: 1, difficulty: 2 },
      { q: "What is L in numbers?", options: ["100", "50", "500", "10"], answer: 1, difficulty: 1 },
      { q: "What is CD in numbers?", options: ["600", "400", "200", "900"], answer: 1, difficulty: 2 },
    ],
  },
  english: {
    spelling: [
      { q: "Which is correct?", options: ["necesary", "necessary", "neccesary", "necessery"], answer: 1, difficulty: 2 },
      { q: "Which is correct?", options: ["environment", "enviroment", "enviorment", "envirment"], answer: 0, difficulty: 2 },
      { q: "Which is correct?", options: ["goverment", "government", "goverment", "govrenment"], answer: 1, difficulty: 1 },
      { q: "Which is correct?", options: ["reccommend", "recomend", "recommend", "recommand"], answer: 2, difficulty: 2 },
      { q: "Which is correct?", options: ["rhythm", "rythm", "rythym", "rhytm"], answer: 0, difficulty: 2 },
      { q: "Which is correct?", options: ["accomodation", "accommodation", "acomodation", "acommodation"], answer: 1, difficulty: 2 },
    ],
    grammar: [
      { q: "What is a relative clause?", options: ["Adds info about a noun using who/which/that", "A command", "A question", "An exclamation"], answer: 0, difficulty: 1 },
      { q: "Which contains a relative clause?", options: ["The dog ran.", "The dog, which was brown, ran.", "Run now!", "Is it cold?"], answer: 1, difficulty: 2 },
      { q: "What is a modal verb?", options: ["can, could, may, might", "run, jump, swim", "big, small, tall", "and, but, or"], answer: 0, difficulty: 1 },
      { q: "Which shows possibility?", options: ["I will go.", "I might go.", "I went.", "I go."], answer: 1, difficulty: 1 },
      { q: "What is a parenthesis?", options: ["Extra info in brackets, dashes or commas", "A type of verb", "A full stop", "A question mark"], answer: 0, difficulty: 2 },
      { q: "Which is a cohesive device?", options: ["however", "table", "blue", "jumped"], answer: 0, difficulty: 2 },
      { q: "Identify the adverbial in: 'After lunch, we played.'", options: ["we", "played", "After lunch", "we played"], answer: 2, difficulty: 1 },
      { q: "Which is in the passive voice?", options: ["The cat chased the mouse.", "The mouse was chased by the cat.", "Cats chase mice.", "Chase the mouse!"], answer: 1, difficulty: 2 },
    ],
    punctuation: [
      { q: "Commas can be used for:", options: ["Lists, clauses, fronted adverbials", "Only lists", "Only questions", "Only names"], answer: 0, difficulty: 1 },
      { q: "A colon is used to:", options: ["End a sentence", "Introduce a list or explanation", "Show a question", "Join two words"], answer: 1, difficulty: 2 },
      { q: "Which uses brackets correctly?", options: ["The dog (a labrador) barked.", "The dog a (labrador) barked.", "(The dog) a labrador barked.", "The (dog a labrador) barked."], answer: 0, difficulty: 1 },
      { q: "Semi-colons join:", options: ["Words", "Two related main clauses", "A title", "Nothing"], answer: 1, difficulty: 2 },
      { q: "Which uses dashes correctly?", options: ["The boy - who was tall - ran.", "The - boy who was tall - ran.", "The boy who - was tall ran.", "- The boy who was tall ran."], answer: 0, difficulty: 2 },
    ],
  },
  science: {
    earth_and_space: [
      { q: "How long does Earth take to orbit the Sun?", options: ["24 hours", "7 days", "365 days", "28 days"], answer: 2, difficulty: 1 },
      { q: "The Moon orbits the:", options: ["Sun", "Earth", "Mars", "Stars"], answer: 1, difficulty: 1 },
      { q: "Day and night are caused by:", options: ["Moon moving", "Earth spinning", "Sun moving", "Clouds"], answer: 1, difficulty: 1 },
      { q: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], answer: 2, difficulty: 1 },
      { q: "The Sun is a:", options: ["Planet", "Moon", "Star", "Asteroid"], answer: 2, difficulty: 1 },
      { q: "Earth rotates once every:", options: ["12 hours", "24 hours", "7 days", "365 days"], answer: 1, difficulty: 1 },
    ],
    forces: [
      { q: "Gravity pulls objects towards:", options: ["The sky", "The centre of Earth", "The Moon", "Other objects only"], answer: 1, difficulty: 1 },
      { q: "What slows a parachute down?", options: ["Gravity", "Air resistance", "Friction", "Magnetism"], answer: 1, difficulty: 1 },
      { q: "Which reduces friction?", options: ["Sandpaper", "Oil", "Glue", "Velcro"], answer: 1, difficulty: 1 },
      { q: "A lever is a type of:", options: ["Force", "Simple machine", "Material", "Energy"], answer: 1, difficulty: 1 },
      { q: "Water resistance acts on objects moving through:", options: ["Air", "Water", "Soil", "Space"], answer: 1, difficulty: 1 },
      { q: "Which has more air resistance?", options: ["Flat paper", "Scrunched paper ball", "Same", "Cannot tell"], answer: 0, difficulty: 2 },
    ],
    life_cycles: [
      { q: "Which animal goes through metamorphosis?", options: ["Dog", "Cat", "Frog", "Horse"], answer: 2, difficulty: 1 },
      { q: "What is the correct order for a frog?", options: ["Egg, tadpole, froglet, frog", "Tadpole, egg, frog, froglet", "Frog, egg, tadpole, froglet", "Egg, frog, tadpole, froglet"], answer: 0, difficulty: 1 },
      { q: "How do mammals reproduce?", options: ["Lay eggs", "Give birth to live young", "Budding", "Splitting"], answer: 1, difficulty: 1 },
      { q: "What do plants need for pollination?", options: ["Wind or insects", "Only rain", "Only soil", "Only darkness"], answer: 0, difficulty: 1 },
      { q: "Gestation means:", options: ["Eating food", "Growing feathers", "Carrying young before birth", "Laying eggs"], answer: 2, difficulty: 2 },
    ],
    properties_of_materials: [
      { q: "Which is a reversible change?", options: ["Burning", "Melting ice", "Cooking egg", "Rusting"], answer: 1, difficulty: 1 },
      { q: "Which is an irreversible change?", options: ["Freezing water", "Melting chocolate", "Burning wood", "Dissolving sugar"], answer: 2, difficulty: 1 },
      { q: "Which material is a thermal insulator?", options: ["Metal", "Wood", "Water", "Aluminium"], answer: 1, difficulty: 1 },
      { q: "Dissolving salt in water is:", options: ["Irreversible", "Reversible", "Chemical change", "Burning"], answer: 1, difficulty: 2 },
      { q: "Which mixture can be separated by filtering?", options: ["Salt and water", "Sand and water", "Sugar and water", "Ink and water"], answer: 1, difficulty: 1 },
      { q: "A good electrical conductor is:", options: ["Rubber", "Plastic", "Copper", "Glass"], answer: 2, difficulty: 1 },
    ],
    human_body: [
      { q: "At what age does puberty typically start?", options: ["5-7", "8-13", "15-18", "3-5"], answer: 1, difficulty: 1 },
      { q: "A baby develops inside the:", options: ["Stomach", "Uterus", "Heart", "Lungs"], answer: 1, difficulty: 1 },
      { q: "The human body changes during:", options: ["Sleeping only", "Growth and aging", "Eating only", "Reading"], answer: 1, difficulty: 1 },
      { q: "Which is a stage of human life?", options: ["Tadpole", "Froglet", "Toddler", "Caterpillar"], answer: 2, difficulty: 1 },
    ],
  },
};
