module.exports = {
  maths: {
    multiplication: [
      { q: "What is 7 × 8?", options: ["54", "56", "58", "48"], answer: 1, difficulty: 1 },
      { q: "What is 9 × 7?", options: ["63", "56", "72", "54"], answer: 0, difficulty: 1 },
      { q: "What is 12 × 6?", options: ["62", "66", "72", "78"], answer: 2, difficulty: 1 },
      { q: "What is 11 × 9?", options: ["99", "88", "109", "91"], answer: 0, difficulty: 2 },
      { q: "What is 25 × 4?", options: ["75", "90", "100", "125"], answer: 2, difficulty: 1 },
    ],
    division: [
      { q: "What is 84 ÷ 7?", options: ["11", "12", "13", "14"], answer: 1, difficulty: 1 },
      { q: "What is 96 ÷ 8?", options: ["11", "12", "13", "14"], answer: 1, difficulty: 1 },
      { q: "What is 132 ÷ 11?", options: ["11", "12", "13", "14"], answer: 1, difficulty: 2 },
      { q: "What is 156 ÷ 12?", options: ["12", "13", "14", "15"], answer: 1, difficulty: 2 },
      { q: "What is 108 ÷ 9?", options: ["11", "12", "13", "14"], answer: 1, difficulty: 1 },
    ],
    fractions: [
      { q: "What is 1/2 of 48?", options: ["20", "22", "24", "26"], answer: 2, difficulty: 1 },
      { q: "What is 3/4 of 40?", options: ["25", "30", "35", "20"], answer: 1, difficulty: 1 },
      { q: "Which is equivalent to 2/4?", options: ["1/2", "1/3", "2/3", "3/4"], answer: 0, difficulty: 1 },
      { q: "What is 1/5 of 35?", options: ["5", "6", "7", "8"], answer: 2, difficulty: 1 },
      { q: "Add: 1/4 + 1/4 = ?", options: ["2/8", "1/2", "2/4", "Both B and C"], answer: 3, difficulty: 2 },
    ],
    place_value: [
      { q: "What is the value of 7 in 3,742?", options: ["7", "70", "700", "7000"], answer: 2, difficulty: 1 },
      { q: "Round 3,678 to the nearest 100", options: ["3,600", "3,700", "3,680", "4,000"], answer: 1, difficulty: 1 },
      { q: "What is 1000 more than 4,562?", options: ["4,662", "5,562", "4,572", "5,062"], answer: 1, difficulty: 1 },
      { q: "Order from smallest: 4521, 4251, 4512", options: ["4251, 4512, 4521", "4512, 4251, 4521", "4521, 4512, 4251", "4251, 4521, 4512"], answer: 0, difficulty: 2 },
      { q: "What number is 100 less than 5,003?", options: ["4,003", "4,903", "5,103", "4,993"], answer: 1, difficulty: 1 },
    ],
    time: [
      { q: "How many seconds in 2 minutes?", options: ["60", "100", "120", "200"], answer: 2, difficulty: 1 },
      { q: "A film starts at 2:45 and lasts 1 hour 30 minutes. When does it end?", options: ["3:45", "4:15", "4:00", "3:15"], answer: 1, difficulty: 2 },
      { q: "How many days in March?", options: ["28", "30", "31", "29"], answer: 2, difficulty: 1 },
      { q: "Convert 3 hours to minutes", options: ["120", "160", "180", "200"], answer: 2, difficulty: 1 },
      { q: "A bus leaves at 09:40 and arrives at 10:15. Journey time?", options: ["25 min", "30 min", "35 min", "45 min"], answer: 2, difficulty: 2 },
    ],
    area_and_perimeter: [
      { q: "Perimeter of a rectangle 8cm by 5cm?", options: ["13cm", "26cm", "40cm", "30cm"], answer: 1, difficulty: 1 },
      { q: "Area of a rectangle 7cm by 4cm?", options: ["22 cm\u00b2", "28 cm\u00b2", "11 cm\u00b2", "32 cm\u00b2"], answer: 1, difficulty: 1 },
      { q: "A square has perimeter 24cm. What is one side?", options: ["4cm", "6cm", "8cm", "12cm"], answer: 1, difficulty: 2 },
      { q: "Area of a square with side 9cm?", options: ["18 cm\u00b2", "36 cm\u00b2", "72 cm\u00b2", "81 cm\u00b2"], answer: 3, difficulty: 1 },
      { q: "Perimeter of a square with side 11cm?", options: ["22cm", "33cm", "44cm", "55cm"], answer: 2, difficulty: 1 },
    ],
    decimals: [
      { q: "What is 0.3 + 0.5?", options: ["0.8", "0.35", "8", "0.08"], answer: 0, difficulty: 1 },
      { q: "Which is bigger: 0.7 or 0.65?", options: ["0.7", "0.65", "Same", "Cannot tell"], answer: 0, difficulty: 1 },
      { q: "What is 2.5 + 1.8?", options: ["3.3", "4.3", "4.13", "3.13"], answer: 1, difficulty: 1 },
      { q: "Round 4.67 to 1 decimal place", options: ["4.6", "4.7", "5.0", "4.0"], answer: 1, difficulty: 2 },
      { q: "What is 3.2 - 1.7?", options: ["1.5", "2.5", "1.7", "2.1"], answer: 0, difficulty: 2 },
    ],
    negative_numbers: [
      { q: "What is 3 - 7?", options: ["-4", "4", "-3", "10"], answer: 0, difficulty: 1 },
      { q: "Which is colder: -5\u00b0C or -2\u00b0C?", options: ["-5\u00b0C", "-2\u00b0C", "Same", "Cannot tell"], answer: 0, difficulty: 1 },
      { q: "What is -3 + 5?", options: ["2", "-2", "8", "-8"], answer: 0, difficulty: 1 },
      { q: "Order from smallest: -1, 3, -4, 0", options: ["-4, -1, 0, 3", "-1, -4, 0, 3", "0, -1, -4, 3", "3, 0, -1, -4"], answer: 0, difficulty: 2 },
      { q: "Temperature is -3\u00b0C. It rises by 7\u00b0C. New temperature?", options: ["4\u00b0C", "10\u00b0C", "-10\u00b0C", "3\u00b0C"], answer: 0, difficulty: 2 },
    ],
    coordinates: [
      { q: "What are the coordinates of the origin?", options: ["(1,1)", "(0,0)", "(0,1)", "(1,0)"], answer: 1, difficulty: 1 },
      { q: "Point A is at (3,5). Move 2 right. New position?", options: ["(5,5)", "(3,7)", "(1,5)", "(3,3)"], answer: 0, difficulty: 1 },
      { q: "Which point is in the first quadrant?", options: ["(-2,3)", "(2,-3)", "(2,3)", "(-2,-3)"], answer: 2, difficulty: 2 },
    ],
  },
  english: {
    spelling: [
      { q: "Which is correct?", options: ["accident", "accedent", "aksident", "acident"], answer: 0, difficulty: 1 },
      { q: "Which is correct?", options: ["intresting", "interesting", "intersting", "intresing"], answer: 1, difficulty: 1 },
      { q: "Which is correct?", options: ["strenth", "strenght", "strength", "strengh"], answer: 2, difficulty: 2 },
      { q: "Which is correct?", options: ["knowlege", "knowledge", "knolege", "knowladge"], answer: 1, difficulty: 2 },
      { q: "Which is correct?", options: ["posession", "possesion", "possession", "posesion"], answer: 2, difficulty: 2 },
      { q: "Which is correct?", options: ["experience", "experiance", "experence", "expirence"], answer: 0, difficulty: 1 },
      { q: "Which is correct?", options: ["discribe", "discibe", "describe", "descirbe"], answer: 2, difficulty: 1 },
      { q: "Which is correct?", options: ["imagin", "imagine", "immagine", "imagene"], answer: 1, difficulty: 1 },
    ],
    punctuation: [
      { q: "Where does the apostrophe go? 'The girls coat'", options: ["The girl's coat", "The girls' coat", "The girl,s coat", "The girls coat'"], answer: 0, difficulty: 1 },
      { q: "Which uses a comma correctly?", options: ["I bought apples oranges and milk.", "I bought apples, oranges and milk.", "I, bought apples oranges and milk.", "I bought, apples oranges and milk."], answer: 1, difficulty: 1 },
      { q: "Which shows possession for plural?", options: ["The dog's bones", "The dogs' bones", "The dogs bones", "The dog,s bones"], answer: 1, difficulty: 2 },
      { q: "Which is correct?", options: ["dont", "don't", "do'nt", "don,t"], answer: 1, difficulty: 1 },
      { q: "Direct speech needs:", options: ["Brackets", "Inverted commas", "Underlining", "Bold text"], answer: 1, difficulty: 1 },
      { q: "Which is punctuated correctly?", options: ["\"Hello\" said Tom.", "\"Hello,\" said Tom.", "Hello, said Tom.", "\"Hello said Tom.\""], answer: 1, difficulty: 2 },
    ],
    grammar: [
      { q: "What is a determiner?", options: ["a, an, the", "run, jump", "big, small", "and, but"], answer: 0, difficulty: 1 },
      { q: "Which is a fronted adverbial?", options: ["The cat sat.", "Quickly, she ran.", "He is tall.", "A red ball."], answer: 1, difficulty: 2 },
      { q: "What type of word is 'carefully'?", options: ["Noun", "Verb", "Adverb", "Adjective"], answer: 2, difficulty: 1 },
      { q: "Which sentence uses an expanded noun phrase?", options: ["The dog ran.", "The big, fluffy dog ran.", "Dogs run.", "He ran fast."], answer: 1, difficulty: 1 },
      { q: "Which is a subordinate conjunction?", options: ["and", "but", "because", "or"], answer: 2, difficulty: 2 },
      { q: "Identify the pronoun: 'She went to school.'", options: ["went", "She", "to", "school"], answer: 1, difficulty: 1 },
      { q: "Which is a noun phrase?", options: ["ran quickly", "the old house", "very happy", "jumped high"], answer: 1, difficulty: 2 },
      { q: "What is the plural of 'child'?", options: ["childs", "childrens", "children", "childes"], answer: 2, difficulty: 1 },
    ],
  },
  science: {
    teeth_and_digestion: [
      { q: "Which type of teeth tear food?", options: ["Incisors", "Canines", "Molars", "Premolars"], answer: 1, difficulty: 1 },
      { q: "Where does digestion begin?", options: ["Stomach", "Mouth", "Small intestine", "Large intestine"], answer: 1, difficulty: 1 },
      { q: "What do molars do?", options: ["Cut food", "Tear food", "Grind food", "Swallow food"], answer: 2, difficulty: 1 },
      { q: "What do incisors do?", options: ["Grind food", "Tear food", "Cut food", "Mix food"], answer: 2, difficulty: 1 },
      { q: "Which organ absorbs nutrients from food?", options: ["Stomach", "Large intestine", "Small intestine", "Mouth"], answer: 2, difficulty: 2 },
      { q: "How many types of teeth do humans have?", options: ["2", "3", "4", "5"], answer: 2, difficulty: 1 },
    ],
    states_of_matter: [
      { q: "What happens to water at 100\u00b0C?", options: ["Freezes", "Boils", "Melts", "Condenses"], answer: 1, difficulty: 1 },
      { q: "Which state of matter can be poured?", options: ["Solid", "Liquid", "Gas", "All of them"], answer: 1, difficulty: 1 },
      { q: "Evaporation turns liquid into:", options: ["Solid", "Gas", "Plasma", "Ice"], answer: 1, difficulty: 1 },
      { q: "At what temperature does water freeze?", options: ["100\u00b0C", "50\u00b0C", "0\u00b0C", "-10\u00b0C"], answer: 2, difficulty: 1 },
      { q: "Which state has particles packed tightly together?", options: ["Solid", "Liquid", "Gas", "All the same"], answer: 0, difficulty: 1 },
      { q: "What is condensation?", options: ["Solid to liquid", "Liquid to gas", "Gas to liquid", "Solid to gas"], answer: 2, difficulty: 2 },
    ],
    electricity: [
      { q: "What provides energy in a circuit?", options: ["Wire", "Bulb", "Battery", "Switch"], answer: 2, difficulty: 1 },
      { q: "A switch in 'off' position creates:", options: ["Complete circuit", "Broken circuit", "Short circuit", "Parallel circuit"], answer: 1, difficulty: 1 },
      { q: "Which material conducts electricity?", options: ["Plastic", "Wood", "Metal", "Rubber"], answer: 2, difficulty: 1 },
      { q: "What does a bulb do in a circuit?", options: ["Stores energy", "Gives out light", "Creates electricity", "Stops current"], answer: 1, difficulty: 1 },
      { q: "A complete circuit needs:", options: ["Battery, wires, component", "Only a battery", "Only wires", "Only a bulb"], answer: 0, difficulty: 1 },
    ],
    sound: [
      { q: "Sound is made by:", options: ["Light", "Vibrations", "Heat", "Colour"], answer: 1, difficulty: 1 },
      { q: "Sound travels fastest through:", options: ["Air", "Water", "Solid", "Vacuum"], answer: 2, difficulty: 2 },
      { q: "What does higher pitch mean?", options: ["Louder sound", "Faster vibrations", "Slower vibrations", "Quieter sound"], answer: 1, difficulty: 1 },
      { q: "Volume is measured in:", options: ["Metres", "Decibels", "Hertz", "Watts"], answer: 1, difficulty: 2 },
      { q: "Can sound travel through a vacuum?", options: ["Yes", "No", "Sometimes", "Only loud sounds"], answer: 1, difficulty: 1 },
    ],
    living_things: [
      { q: "Which is NOT a living thing?", options: ["Tree", "Mushroom", "Rock", "Bacteria"], answer: 2, difficulty: 1 },
      { q: "Living things can be grouped into:", options: ["Colours", "Sizes only", "Species and characteristics", "Shapes only"], answer: 2, difficulty: 1 },
      { q: "A habitat is:", options: ["A type of food", "Where an organism lives", "A body part", "A season"], answer: 1, difficulty: 1 },
      { q: "Which is a vertebrate?", options: ["Snail", "Worm", "Cat", "Spider"], answer: 2, difficulty: 1 },
      { q: "Which is an invertebrate?", options: ["Dog", "Fish", "Bird", "Butterfly"], answer: 3, difficulty: 1 },
    ],
  },
};

