module.exports = {
  maths: {
    integers_and_place_value: [
      { q: "What is -8 + 3?", options: ["-5", "5", "-11", "11"], answer: 0, difficulty: 1 },
      { q: "What is -4 × -3?", options: ["-12", "12", "-7", "7"], answer: 1, difficulty: 1 },
      { q: "What is -15 ÷ 3?", options: ["5", "-5", "3", "-3"], answer: 1, difficulty: 1 },
      { q: "What is (-2)³?", options: ["6", "-6", "8", "-8"], answer: 3, difficulty: 2 },
      { q: "Order from smallest: -3, 1, -7, 4, 0", options: ["-7,-3,0,1,4", "-3,-7,0,1,4", "0,1,-3,-7,4", "4,1,0,-3,-7"], answer: 0, difficulty: 1 },
      { q: "What is -6 - (-4)?", options: ["-10", "-2", "2", "10"], answer: 1, difficulty: 2 },
    ],
    algebra: [
      { q: "Simplify: 3x + 5x - 2x", options: ["6x", "8x", "10x", "4x"], answer: 0, difficulty: 1 },
      { q: "Expand: 4(2x + 3)", options: ["8x + 3", "6x + 7", "8x + 12", "8x + 7"], answer: 2, difficulty: 1 },
      { q: "Solve: 3x + 4 = 19", options: ["x = 3", "x = 4", "x = 5", "x = 6"], answer: 2, difficulty: 1 },
      { q: "Simplify: 2a × 3a", options: ["5a", "6a", "6a²", "5a²"], answer: 2, difficulty: 2 },
      { q: "What is the value of 3x² when x = 4?", options: ["24", "36", "48", "144"], answer: 2, difficulty: 2 },
      { q: "Solve: 5x - 7 = 2x + 8", options: ["x = 3", "x = 5", "x = 7", "x = 1"], answer: 1, difficulty: 2 },
      { q: "Factorise: 6x + 12", options: ["6(x + 2)", "3(2x + 4)", "2(3x + 6)", "All of these"], answer: 3, difficulty: 2 },
      { q: "Simplify: 4x + 3y - x + 2y", options: ["3x + 5y", "5x + 5y", "3x + y", "4x + 5y"], answer: 0, difficulty: 1 },
    ],
    fractions_decimals_percentages: [
      { q: "What is 2/5 + 3/10?", options: ["5/15", "7/10", "1/2", "5/10"], answer: 1, difficulty: 1 },
      { q: "What is 3/4 × 2/5?", options: ["6/20", "3/10", "5/9", "Both A and B"], answer: 3, difficulty: 2 },
      { q: "What is 2/3 ÷ 4/9?", options: ["3/2", "8/27", "1/6", "6/4"], answer: 0, difficulty: 2 },
      { q: "Convert 7/8 to a decimal", options: ["0.78", "0.875", "0.87", "0.785"], answer: 1, difficulty: 1 },
      { q: "What is 35% of 80?", options: ["24", "28", "32", "36"], answer: 1, difficulty: 1 },
      { q: "Increase 60 by 20%", options: ["68", "72", "74", "80"], answer: 1, difficulty: 1 },
      { q: "Decrease 150 by 10%", options: ["130", "135", "140", "145"], answer: 1, difficulty: 1 },
    ],
    ratio_and_proportion: [
      { q: "Share £48 in the ratio 1:3", options: ["£12 and £36", "£16 and £32", "£24 and £24", "£8 and £40"], answer: 0, difficulty: 1 },
      { q: "Simplify 24:36", options: ["2:3", "4:6", "12:18", "3:4"], answer: 0, difficulty: 1 },
      { q: "4 books cost £18. How much do 7 books cost?", options: ["£28.50", "£31.50", "£35.00", "£25.50"], answer: 1, difficulty: 2 },
      { q: "A map scale is 1:25000. 4cm on map = real distance?", options: ["100m", "250m", "1km", "10km"], answer: 2, difficulty: 2 },
      { q: "Ratio of boys:girls is 3:5. 40 students total. How many boys?", options: ["12", "15", "18", "24"], answer: 1, difficulty: 2 },
    ],
    angles: [
      { q: "Angles on a straight line add up to:", options: ["90°", "180°", "270°", "360°"], answer: 1, difficulty: 1 },
      { q: "Angles around a point add up to:", options: ["90°", "180°", "270°", "360°"], answer: 3, difficulty: 1 },
      { q: "Vertically opposite angles are:", options: ["Supplementary", "Equal", "90°", "180°"], answer: 1, difficulty: 1 },
      { q: "Co-interior angles add up to:", options: ["90°", "180°", "270°", "360°"], answer: 1, difficulty: 2 },
      { q: "Alternate angles are:", options: ["Equal", "Add to 180°", "Add to 90°", "Add to 360°"], answer: 0, difficulty: 1 },
      { q: "An angle of 135° is:", options: ["Acute", "Right", "Obtuse", "Reflex"], answer: 2, difficulty: 1 },
    ],
    area_and_perimeter: [
      { q: "Area of a triangle: base 12cm, height 7cm?", options: ["84 cm²", "42 cm²", "19 cm²", "38 cm²"], answer: 1, difficulty: 1 },
      { q: "Area of a trapezium: parallel sides 6cm and 10cm, height 5cm?", options: ["40 cm²", "50 cm²", "80 cm²", "30 cm²"], answer: 0, difficulty: 2 },
      { q: "Area of a parallelogram: base 9cm, height 6cm?", options: ["15 cm²", "27 cm²", "54 cm²", "108 cm²"], answer: 2, difficulty: 1 },
      { q: "Circumference of a circle, radius 7cm? (π = 22/7)", options: ["22cm", "44cm", "88cm", "154cm"], answer: 1, difficulty: 1 },
      { q: "Area of a circle, radius 5cm? (π = 3.14)", options: ["31.4 cm²", "78.5 cm²", "15.7 cm²", "157 cm²"], answer: 1, difficulty: 2 },
    ],
    sequences: [
      { q: "Next term: 2, 6, 10, 14, ...?", options: ["16", "17", "18", "20"], answer: 2, difficulty: 1 },
      { q: "nth term of 3, 5, 7, 9 is:", options: ["2n + 1", "2n - 1", "3n", "n + 2"], answer: 0, difficulty: 2 },
      { q: "Next term: 1, 4, 9, 16, ...?", options: ["20", "21", "25", "36"], answer: 2, difficulty: 1 },
      { q: "What is the 10th term of: 5, 8, 11, 14, ...?", options: ["29", "32", "35", "38"], answer: 1, difficulty: 2 },
      { q: "Next term: 2, 5, 10, 17, ...?", options: ["24", "25", "26", "28"], answer: 2, difficulty: 2 },
    ],
    probability: [
      { q: "A fair dice is rolled. P(even number)?", options: ["1/6", "1/3", "1/2", "2/3"], answer: 2, difficulty: 1 },
      { q: "A bag has 3 red and 7 blue. P(red)?", options: ["3/7", "3/10", "7/10", "1/3"], answer: 1, difficulty: 1 },
      { q: "P(event) = 0.3. P(not event)?", options: ["0.3", "0.7", "1.3", "0"], answer: 1, difficulty: 1 },
      { q: "A coin is flipped 3 times. P(3 heads)?", options: ["1/2", "1/4", "1/8", "3/8"], answer: 2, difficulty: 2 },
      { q: "Theoretical probability of rolling a 5 on a fair dice?", options: ["1/5", "1/6", "5/6", "1/3"], answer: 1, difficulty: 1 },
    ],
    transformations: [
      { q: "Reflection in x-axis: (3, 4) becomes?", options: ["(3, -4)", "(-3, 4)", "(-3, -4)", "(4, 3)"], answer: 0, difficulty: 1 },
      { q: "Translation by vector (2, -3): (1, 5) becomes?", options: ["(3, 2)", "(3, 8)", "(-1, 8)", "(-1, 2)"], answer: 0, difficulty: 1 },
      { q: "Rotation 180° about origin: (2, 3) becomes?", options: ["(-2, -3)", "(-2, 3)", "(2, -3)", "(3, 2)"], answer: 0, difficulty: 2 },
      { q: "Which transformation preserves shape and size?", options: ["Enlargement", "Reflection", "Stretching", "Squashing"], answer: 1, difficulty: 1 },
    ],
  },
  science: {
    cells: [
      { q: "Which is found in plant cells but NOT animal cells?", options: ["Nucleus", "Cell membrane", "Chloroplast", "Cytoplasm"], answer: 2, difficulty: 1 },
      { q: "What is the function of the nucleus?", options: ["Energy production", "Controls the cell", "Photosynthesis", "Storage"], answer: 1, difficulty: 1 },
      { q: "Which organelle carries out respiration?", options: ["Nucleus", "Ribosome", "Mitochondria", "Vacuole"], answer: 2, difficulty: 2 },
      { q: "Cell membrane function:", options: ["Controls what enters/leaves", "Stores water", "Makes protein", "Produces energy"], answer: 0, difficulty: 1 },
      { q: "What do ribosomes make?", options: ["Energy", "Protein", "Sugar", "Fat"], answer: 1, difficulty: 2 },
      { q: "A microscope is used to:", options: ["Heat things", "Magnify small objects", "Weigh objects", "Measure temperature"], answer: 1, difficulty: 1 },
    ],
    particles: [
      { q: "In which state are particles closest together?", options: ["Solid", "Liquid", "Gas", "All the same"], answer: 0, difficulty: 1 },
      { q: "What happens to particles when heated?", options: ["Move slower", "Move faster", "Stop", "Get smaller"], answer: 1, difficulty: 1 },
      { q: "Diffusion is:", options: ["Particles moving from high to low concentration", "Heating a solid", "Freezing water", "Mixing oil and water"], answer: 0, difficulty: 2 },
      { q: "Gas particles:", options: ["Are fixed in position", "Vibrate in place", "Move freely in all directions", "Slide past each other"], answer: 2, difficulty: 1 },
      { q: "Which change of state is sublimation?", options: ["Solid to liquid", "Liquid to gas", "Solid to gas", "Gas to solid"], answer: 2, difficulty: 2 },
    ],
    elements_compounds_mixtures: [
      { q: "An element contains:", options: ["Two types of atom", "One type of atom only", "Molecules only", "Mixtures"], answer: 1, difficulty: 1 },
      { q: "A compound is:", options: ["One type of atom", "Two or more elements chemically joined", "A mixture", "Pure water only"], answer: 1, difficulty: 1 },
      { q: "Which is a mixture?", options: ["Water (H₂O)", "Salt (NaCl)", "Air", "Carbon dioxide"], answer: 2, difficulty: 1 },
      { q: "The chemical formula H₂O means:", options: ["2 hydrogen, 1 oxygen", "1 hydrogen, 2 oxygen", "2 water molecules", "Hydrogen only"], answer: 0, difficulty: 1 },
      { q: "Which separation method uses boiling points?", options: ["Filtration", "Distillation", "Magnetism", "Sieving"], answer: 1, difficulty: 2 },
    ],
    acids_and_alkalis: [
      { q: "pH 7 is:", options: ["Acidic", "Neutral", "Alkaline", "Corrosive"], answer: 1, difficulty: 1 },
      { q: "Which indicator changes colour in acid/alkali?", options: ["Thermometer", "Litmus", "Ruler", "Magnifying glass"], answer: 1, difficulty: 1 },
      { q: "A strong acid has pH:", options: ["1-2", "6-7", "7-8", "12-14"], answer: 0, difficulty: 1 },
      { q: "Neutralisation produces:", options: ["Acid + gas", "Salt + water", "Base + acid", "Metal + oxygen"], answer: 1, difficulty: 1 },
      { q: "Which is an alkali?", options: ["Lemon juice", "Vinegar", "Soap", "Cola"], answer: 2, difficulty: 1 },
    ],
    forces: [
      { q: "What is the unit of force?", options: ["Joule", "Newton", "Watt", "Pascal"], answer: 1, difficulty: 1 },
      { q: "A force that opposes motion is:", options: ["Gravity", "Thrust", "Friction", "Upthrust"], answer: 2, difficulty: 1 },
      { q: "If forces are balanced, an object:", options: ["Accelerates", "Stays at constant speed or rest", "Always stops", "Always moves"], answer: 1, difficulty: 1 },
      { q: "Speed = distance ÷ time. 60km in 2 hours =", options: ["120 km/h", "30 km/h", "62 km/h", "58 km/h"], answer: 1, difficulty: 1 },
      { q: "Weight is caused by:", options: ["Air", "Magnetism", "Gravity", "Friction"], answer: 2, difficulty: 1 },
      { q: "A resultant force of zero means:", options: ["Object speeds up", "Object is stationary or constant speed", "Object slows down", "Object changes direction"], answer: 1, difficulty: 2 },
    ],
    energy: [
      { q: "Which is a renewable energy source?", options: ["Coal", "Oil", "Wind", "Gas"], answer: 2, difficulty: 1 },
      { q: "Fossil fuels include:", options: ["Wood, solar, wind", "Coal, oil, natural gas", "Nuclear, wave, tidal", "Biomass, solar, wind"], answer: 1, difficulty: 1 },
      { q: "Energy cannot be:", options: ["Transferred", "Stored", "Created or destroyed", "Measured"], answer: 2, difficulty: 1 },
      { q: "Kinetic energy is energy of:", options: ["Height", "Movement", "Heat", "Stored chemicals"], answer: 1, difficulty: 1 },
      { q: "Gravitational potential energy depends on:", options: ["Speed", "Height", "Colour", "Temperature"], answer: 1, difficulty: 1 },
      { q: "What unit is energy measured in?", options: ["Newtons", "Watts", "Joules", "Volts"], answer: 2, difficulty: 1 },
    ],
    reproduction: [
      { q: "Where is pollen produced in a flower?", options: ["Stigma", "Anther", "Ovary", "Petal"], answer: 1, difficulty: 1 },
      { q: "Pollination is transfer of pollen from:", options: ["Anther to stigma", "Stigma to anther", "Root to leaf", "Leaf to flower"], answer: 0, difficulty: 1 },
      { q: "In humans, fertilisation occurs in the:", options: ["Uterus", "Ovary", "Fallopian tube", "Vagina"], answer: 2, difficulty: 2 },
      { q: "The male reproductive cell is:", options: ["Egg", "Sperm", "Embryo", "Ovum"], answer: 1, difficulty: 1 },
      { q: "Seed dispersal can happen by:", options: ["Wind, animals, water, explosion", "Only wind", "Only animals", "Only water"], answer: 0, difficulty: 1 },
    ],
    space: [
      { q: "Which planet is known as the Red Planet?", options: ["Venus", "Jupiter", "Mars", "Saturn"], answer: 2, difficulty: 1 },
      { q: "The Sun is:", options: ["A planet", "A star", "A moon", "An asteroid"], answer: 1, difficulty: 1 },
      { q: "What causes tides on Earth?", options: ["Wind", "Moon's gravity", "Sun's heat", "Earth spinning"], answer: 1, difficulty: 2 },
      { q: "A year on Earth is:", options: ["365.25 days", "360 days", "24 hours", "28 days"], answer: 0, difficulty: 1 },
      { q: "Which is the largest planet?", options: ["Saturn", "Neptune", "Jupiter", "Uranus"], answer: 2, difficulty: 1 },
    ],
  },
};
