module.exports = {
  maths: {
    algebra: [
      { q: "If a = 3, what is 4a + 2?", options: ["10", "12", "14", "16"], answer: 2, difficulty: 1 },
      { q: "Solve: 2x = 14", options: ["x = 5", "x = 6", "x = 7", "x = 8"], answer: 2, difficulty: 1 },
      { q: "Find the missing number: ? + 5 = 12", options: ["5", "6", "7", "8"], answer: 2, difficulty: 1 },
      { q: "If n = 4, what is 3n - 5?", options: ["5", "7", "9", "12"], answer: 1, difficulty: 1 },
      { q: "Solve: x/3 = 9", options: ["3", "6", "27", "12"], answer: 2, difficulty: 2 },
      { q: "What is the next term: 2, 5, 8, 11, ...?", options: ["12", "13", "14", "15"], answer: 2, difficulty: 1 },
      { q: "Write an expression: 5 more than n", options: ["5n", "n - 5", "n + 5", "n/5"], answer: 2, difficulty: 1 },
    ],
    fractions_decimals_percentages: [
      { q: "What is 3/8 + 1/4?", options: ["4/12", "5/8", "1/2", "7/8"], answer: 1, difficulty: 2 },
      { q: "What is 2/3 × 6?", options: ["2", "3", "4", "12"], answer: 2, difficulty: 1 },
      { q: "What is 3/4 ÷ 2?", options: ["3/8", "3/2", "6/4", "1/2"], answer: 0, difficulty: 2 },
      { q: "Convert 0.35 to a fraction", options: ["35/10", "7/20", "35/1000", "7/10"], answer: 1, difficulty: 2 },
      { q: "What is 15% of 60?", options: ["6", "9", "12", "15"], answer: 1, difficulty: 1 },
      { q: "What is 1/5 as a percentage?", options: ["5%", "10%", "15%", "20%"], answer: 3, difficulty: 1 },
      { q: "Order: 0.6, 3/5, 65%. Smallest to largest?", options: ["All equal", "0.6, 3/5, 65%", "3/5, 0.6, 65%", "65%, 0.6, 3/5"], answer: 2, difficulty: 2 },
      { q: "What is 40% of 150?", options: ["40", "50", "60", "70"], answer: 2, difficulty: 1 },
    ],
    ratio: [
      { q: "Simplify the ratio 8:12", options: ["2:3", "4:6", "1:2", "8:12"], answer: 0, difficulty: 1 },
      { q: "Share £30 in the ratio 2:3. Larger share?", options: ["£12", "£15", "£18", "£20"], answer: 2, difficulty: 1 },
      { q: "Ratio of red to blue is 1:3. 24 total. How many blue?", options: ["6", "8", "12", "18"], answer: 3, difficulty: 2 },
      { q: "Scale: 1cm = 5km. Map distance 4cm = real?", options: ["9km", "20km", "15km", "25km"], answer: 1, difficulty: 1 },
      { q: "3 pens cost £2.10. How much for 7 pens?", options: ["£4.20", "£4.90", "£5.60", "£6.30"], answer: 1, difficulty: 2 },
    ],
    geometry: [
      { q: "What is the area of a triangle: base 8cm, height 5cm?", options: ["40 cm²", "20 cm²", "13 cm²", "80 cm²"], answer: 1, difficulty: 1 },
      { q: "What is the area of a parallelogram: base 9cm, height 4cm?", options: ["13 cm²", "18 cm²", "36 cm²", "72 cm²"], answer: 2, difficulty: 1 },
      { q: "A circle has radius 4cm. What is its diameter?", options: ["2cm", "4cm", "8cm", "16cm"], answer: 2, difficulty: 1 },
      { q: "Volume of a cube with side 5cm?", options: ["15 cm³", "25 cm³", "125 cm³", "150 cm³"], answer: 2, difficulty: 1 },
      { q: "Angles in a quadrilateral sum to:", options: ["180°", "270°", "360°", "540°"], answer: 2, difficulty: 1 },
      { q: "A shape has vertices at (1,1), (4,1), (4,3), (1,3). What shape?", options: ["Triangle", "Rectangle", "Pentagon", "Hexagon"], answer: 1, difficulty: 2 },
    ],
    statistics: [
      { q: "Mean of 4, 6, 8, 10, 12?", options: ["6", "7", "8", "9"], answer: 2, difficulty: 1 },
      { q: "What is the mode of: 3, 5, 5, 7, 9?", options: ["3", "5", "7", "9"], answer: 1, difficulty: 1 },
      { q: "What is the range of: 2, 8, 4, 11, 3?", options: ["8", "9", "11", "6"], answer: 1, difficulty: 1 },
      { q: "Median of: 1, 3, 5, 7, 9?", options: ["3", "5", "7", "9"], answer: 1, difficulty: 1 },
      { q: "Mean of 10, 20, 30?", options: ["15", "20", "25", "30"], answer: 1, difficulty: 1 },
      { q: "A pie chart shows 1/4 like football. What angle?", options: ["45°", "60°", "90°", "120°"], answer: 2, difficulty: 2 },
    ],
    long_division: [
      { q: "What is 858 ÷ 6?", options: ["133", "143", "153", "163"], answer: 1, difficulty: 2 },
      { q: "What is 972 ÷ 4?", options: ["233", "238", "243", "248"], answer: 2, difficulty: 2 },
      { q: "What is 1035 ÷ 5?", options: ["207", "217", "197", "205"], answer: 0, difficulty: 1 },
      { q: "What is 2016 ÷ 8?", options: ["242", "248", "252", "256"], answer: 2, difficulty: 2 },
    ],
    order_of_operations: [
      { q: "What is 3 + 4 × 2?", options: ["14", "11", "10", "9"], answer: 1, difficulty: 1 },
      { q: "What is (5 + 3) × 2?", options: ["11", "13", "16", "8"], answer: 2, difficulty: 1 },
      { q: "What is 20 - 4 × 3?", options: ["8", "48", "12", "14"], answer: 0, difficulty: 2 },
      { q: "What is 2 + 3²?", options: ["25", "11", "10", "7"], answer: 1, difficulty: 2 },
      { q: "What is (10 - 4) ÷ 2?", options: ["2", "3", "4", "5"], answer: 1, difficulty: 1 },
    ],
  },
  english: {
    spelling: [
      { q: "Which is correct?", options: ["apparant", "apparent", "aparent", "apparrent"], answer: 1, difficulty: 2 },
      { q: "Which is correct?", options: ["conscious", "concious", "consious", "conshus"], answer: 0, difficulty: 2 },
      { q: "Which is correct?", options: ["existance", "existence", "existense", "existince"], answer: 1, difficulty: 2 },
      { q: "Which is correct?", options: ["mischievous", "mischevious", "mischivous", "mischievious"], answer: 0, difficulty: 2 },
      { q: "Which is correct?", options: ["privlege", "privelege", "privilege", "priviledge"], answer: 2, difficulty: 2 },
      { q: "Which is correct?", options: ["recognise", "reconise", "recongise", "recoginse"], answer: 0, difficulty: 1 },
    ],
    grammar: [
      { q: "What is the subjunctive mood?", options: ["If I were you...", "I am happy.", "Run!", "He is tall."], answer: 0, difficulty: 2 },
      { q: "Which is a formal sentence?", options: ["It's gonna rain.", "It is going to rain.", "Gonna rain soon.", "Rain's coming."], answer: 1, difficulty: 1 },
      { q: "What is an antonym of 'ancient'?", options: ["Old", "Modern", "Broken", "Large"], answer: 1, difficulty: 1 },
      { q: "What is a synonym of 'happy'?", options: ["Sad", "Angry", "Joyful", "Tired"], answer: 2, difficulty: 1 },
      { q: "Which is active voice?", options: ["The ball was kicked by Tom.", "Tom kicked the ball.", "The ball got kicked.", "It was kicked."], answer: 1, difficulty: 1 },
      { q: "Which is passive voice?", options: ["She wrote the letter.", "The letter was written by her.", "She is writing.", "Write the letter!"], answer: 1, difficulty: 1 },
      { q: "A semi-colon separates:", options: ["Words in a list", "Two related clauses", "A title", "A question"], answer: 1, difficulty: 2 },
      { q: "What is an ellipsis (...) used for?", options: ["Ending a question", "Showing missing words or suspense", "Starting a sentence", "Showing anger"], answer: 1, difficulty: 1 },
    ],
    reading_comprehension: [
      { q: "What does 'infer' mean?", options: ["Copy exactly", "Work out from clues", "Guess randomly", "Ask someone"], answer: 1, difficulty: 1 },
      { q: "A biography is:", options: ["A made-up story", "Someone's life story written by another", "A poem", "A recipe"], answer: 1, difficulty: 1 },
      { q: "An autobiography is:", options: ["A made-up story", "Someone's life story written by themselves", "A poem", "A play"], answer: 1, difficulty: 1 },
      { q: "What is a theme?", options: ["The title", "The main message or idea", "The setting", "The characters"], answer: 1, difficulty: 2 },
      { q: "Figurative language includes:", options: ["Only facts", "Similes and metaphors", "Only dates", "Addresses"], answer: 1, difficulty: 1 },
    ],
  },
  science: {
    evolution: [
      { q: "Who is famous for the theory of evolution?", options: ["Newton", "Einstein", "Darwin", "Galileo"], answer: 2, difficulty: 1 },
      { q: "Fossils are found in which type of rock?", options: ["Igneous", "Sedimentary", "Metamorphic", "All types"], answer: 1, difficulty: 1 },
      { q: "Adaptation means:", options: ["Getting bigger", "Features that help survival", "Changing colour", "Moving faster only"], answer: 1, difficulty: 1 },
      { q: "Offspring inherit characteristics from:", options: ["Only mother", "Only father", "Both parents", "Friends"], answer: 2, difficulty: 1 },
      { q: "Natural selection means:", options: ["Humans choose animals", "Best adapted survive", "All animals are the same", "Animals choose homes"], answer: 1, difficulty: 2 },
      { q: "Which provides evidence for evolution?", options: ["Fossils", "Weather", "Computers", "Books"], answer: 0, difficulty: 1 },
    ],
    living_things: [
      { q: "Which is a microorganism?", options: ["Dog", "Tree", "Bacteria", "Fish"], answer: 2, difficulty: 1 },
      { q: "Carl Linnaeus is known for:", options: ["Discovering gravity", "Classifying living things", "Inventing electricity", "Finding fossils"], answer: 1, difficulty: 2 },
      { q: "Which kingdom includes mushrooms?", options: ["Plants", "Animals", "Fungi", "Bacteria"], answer: 2, difficulty: 1 },
      { q: "Mammals are classified by:", options: ["Having scales", "Warm-blooded, fur, live young", "Having feathers", "Living in water"], answer: 1, difficulty: 1 },
      { q: "Which is a characteristic of insects?", options: ["4 legs", "6 legs", "8 legs", "No legs"], answer: 1, difficulty: 1 },
    ],
    electricity: [
      { q: "What is voltage measured in?", options: ["Amps", "Volts", "Watts", "Ohms"], answer: 1, difficulty: 1 },
      { q: "Adding more batteries to a circuit makes a bulb:", options: ["Dimmer", "Brighter", "Same", "Turn off"], answer: 1, difficulty: 1 },
      { q: "In a circuit diagram, what does a straight line represent?", options: ["Battery", "Wire", "Bulb", "Switch"], answer: 1, difficulty: 1 },
      { q: "More bulbs in a series circuit makes each bulb:", options: ["Brighter", "Dimmer", "Same", "Flash"], answer: 1, difficulty: 2 },
      { q: "Which component measures voltage?", options: ["Ammeter", "Voltmeter", "Battery", "Resistor"], answer: 1, difficulty: 1 },
      { q: "A short circuit can cause:", options: ["Nothing", "Overheating/fire", "Brighter light", "Louder sound"], answer: 1, difficulty: 2 },
    ],
    light: [
      { q: "Light travels in:", options: ["Curves", "Straight lines", "Circles", "Zigzags"], answer: 1, difficulty: 1 },
      { q: "We see objects because:", options: ["Our eyes glow", "Light reflects off them into our eyes", "Objects produce light", "We touch them"], answer: 1, difficulty: 1 },
      { q: "What are the colours of the rainbow?", options: ["5 colours", "6 colours", "7 colours", "8 colours"], answer: 2, difficulty: 1 },
      { q: "Shadows are formed because light:", options: ["Bends around objects", "Cannot pass through opaque objects", "Is absorbed", "Changes colour"], answer: 1, difficulty: 1 },
      { q: "As light source moves further away, shadow:", options: ["Gets bigger", "Gets smaller", "Stays same", "Disappears"], answer: 1, difficulty: 2 },
    ],
    human_body: [
      { q: "The heart is part of which system?", options: ["Digestive", "Respiratory", "Circulatory", "Nervous"], answer: 2, difficulty: 1 },
      { q: "What carries blood away from the heart?", options: ["Veins", "Arteries", "Capillaries", "Nerves"], answer: 1, difficulty: 1 },
      { q: "The lungs are part of which system?", options: ["Digestive", "Respiratory", "Circulatory", "Skeletal"], answer: 1, difficulty: 1 },
      { q: "What is the main function of the liver?", options: ["Pumping blood", "Filtering toxins", "Breathing", "Digesting food"], answer: 1, difficulty: 2 },
      { q: "How many chambers does the heart have?", options: ["2", "3", "4", "5"], answer: 2, difficulty: 1 },
      { q: "What do red blood cells carry?", options: ["Food", "Oxygen", "Water", "Germs"], answer: 1, difficulty: 1 },
    ],
    sats_maths: [
      { q: "What is 3/4 of 96?", options: ["48", "64", "72", "80"], answer: 2, difficulty: 2 },
      { q: "A rectangle has perimeter 36cm, length 10cm. Width?", options: ["6cm", "7cm", "8cm", "9cm"], answer: 2, difficulty: 2 },
      { q: "What is 2.4 x 6?", options: ["12.4", "13.4", "14.4", "15.4"], answer: 2, difficulty: 1 },
      { q: "Round 34,756 to the nearest 1000", options: ["34,000", "34,700", "35,000", "34,800"], answer: 2, difficulty: 1 },
      { q: "What is 60% of 45?", options: ["24", "25", "27", "30"], answer: 2, difficulty: 2 },
      { q: "A train departs 08:47, arrives 11:15. Journey time?", options: ["2h 28min", "2h 32min", "2h 38min", "2h 18min"], answer: 0, difficulty: 2 },
      { q: "Missing angle in triangle: 65, 72, ?", options: ["33", "43", "53", "63"], answer: 1, difficulty: 2 },
      { q: "What is 1/3 of 2/5?", options: ["3/5", "2/15", "2/8", "3/15"], answer: 1, difficulty: 2 },
      { q: "Simplify 3/4 + 1/8", options: ["4/12", "7/8", "4/8", "5/8"], answer: 1, difficulty: 2 },
      { q: "What is 15% of 80?", options: ["8", "10", "12", "15"], answer: 2, difficulty: 1 },
      { q: "What is 4.56 x 100?", options: ["45.6", "456", "4560", "0.0456"], answer: 1, difficulty: 1 },
      { q: "What is 7/10 - 2/5?", options: ["5/5", "3/10", "1/2", "1/10"], answer: 1, difficulty: 2 },
      { q: "A cuboid is 4cm x 3cm x 5cm. Volume?", options: ["12 cm3", "35 cm3", "60 cm3", "120 cm3"], answer: 2, difficulty: 1 },
      { q: "What is the mean of 3, 7, 5, 9, 6?", options: ["5", "6", "7", "8"], answer: 1, difficulty: 1 },
      { q: "Express 0.72 as a fraction in simplest form", options: ["72/100", "18/25", "7/10", "36/50"], answer: 1, difficulty: 2 },
      { q: "Two angles in a triangle are 58 and 47. Third angle?", options: ["65", "75", "85", "95"], answer: 1, difficulty: 1 },
      { q: "What is 3 squared + 4 squared?", options: ["7", "12", "25", "49"], answer: 2, difficulty: 2 },
      { q: "A shop gives 1/3 off £45. Sale price?", options: ["£15", "£25", "£30", "£35"], answer: 2, difficulty: 1 },
      { q: "How many faces does a triangular prism have?", options: ["3", "4", "5", "6"], answer: 2, difficulty: 1 },
      { q: "0.125 as a fraction?", options: ["1/4", "1/8", "1/5", "1/10"], answer: 1, difficulty: 2 },
      { q: "Coordinates of midpoint of (2,4) and (6,8)?", options: ["(3,5)", "(4,6)", "(8,12)", "(4,4)"], answer: 1, difficulty: 2 },
      { q: "A car travels 150 miles in 3 hours. Speed?", options: ["45 mph", "50 mph", "55 mph", "60 mph"], answer: 1, difficulty: 1 },
      { q: "What is 5/6 of 42?", options: ["30", "35", "36", "40"], answer: 1, difficulty: 2 },
      { q: "Exterior angle of a regular hexagon?", options: ["30", "45", "60", "90"], answer: 2, difficulty: 2 },
    ],
    sats_english: [
      { q: "Which word class is rapidly?", options: ["Noun", "Verb", "Adjective", "Adverb"], answer: 3, difficulty: 1 },
      { q: "Which is a prefix?", options: ["tion", "ly", "ful", "dis"], answer: 3, difficulty: 1 },
      { q: "Which is a suffix?", options: ["pre", "un", "mis", "ness"], answer: 3, difficulty: 1 },
      { q: "Which is past perfect tense?", options: ["She runs.", "She ran.", "She had run.", "She will run."], answer: 2, difficulty: 2 },
      { q: "What does prefix anti mean?", options: ["Before", "Against", "Under", "After"], answer: 1, difficulty: 1 },
      { q: "Which is a compound sentence?", options: ["She ran.", "She ran and he jumped.", "Because she ran.", "Running fast."], answer: 1, difficulty: 1 },
      { q: "Persuasive writing aims to:", options: ["Entertain", "Inform", "Convince the reader", "Tell a story"], answer: 2, difficulty: 1 },
      { q: "Homophone of there?", options: ["Here", "Their", "Were", "Where"], answer: 1, difficulty: 1 },
      { q: "Root word in uncomfortable?", options: ["un", "comfort", "able", "uncomfort"], answer: 1, difficulty: 1 },
      { q: "Which uses subjunctive mood?", options: ["I am here.", "If I were you.", "She went.", "Run!"], answer: 1, difficulty: 2 },
      { q: "What type of clause begins with when, if, because?", options: ["Main clause", "Subordinate clause", "Noun phrase", "Verb phrase"], answer: 1, difficulty: 1 },
      { q: "Which is a determiner?", options: ["quickly", "the", "run", "happy"], answer: 1, difficulty: 1 },
      { q: "What is an antonym of generous?", options: ["Kind", "Selfish", "Brave", "Tall"], answer: 1, difficulty: 1 },
      { q: "Which uses a colon correctly?", options: ["I need: eggs.", "I need eggs: milk.", "I need these items: eggs, milk and bread.", "I: need eggs."], answer: 2, difficulty: 2 },
      { q: "What is a synonym of enormous?", options: ["Tiny", "Huge", "Fast", "Old"], answer: 1, difficulty: 1 },
      { q: "Which is a preposition?", options: ["run", "behind", "happy", "and"], answer: 1, difficulty: 1 },
      { q: "Identify the subordinate clause: I stayed inside because it rained.", options: ["I stayed inside", "because it rained", "I stayed", "inside because"], answer: 1, difficulty: 2 },
      { q: "What punctuation introduces direct speech?", options: ["Full stop", "Comma", "Inverted commas", "Brackets"], answer: 2, difficulty: 1 },
      { q: "Which has a fronted adverbial?", options: ["The cat sat.", "Slowly, the cat sat.", "Cats sit slowly.", "The slow cat."], answer: 1, difficulty: 1 },
      { q: "What is the plural of sheep?", options: ["sheeps", "sheepes", "sheep", "sheepies"], answer: 2, difficulty: 1 },
      { q: "Which word means to look quickly?", options: ["Stare", "Glance", "Gaze", "Watch"], answer: 1, difficulty: 1 },
      { q: "What is an apostrophe used for?", options: ["Possession and contraction", "Plurals", "Questions", "Exclamations"], answer: 0, difficulty: 1 },
      { q: "Which is a complex sentence?", options: ["I ran.", "I ran and jumped.", "Although tired, I ran.", "Run!"], answer: 2, difficulty: 2 },
      { q: "The suffix -tion usually creates a:", options: ["Verb", "Adjective", "Noun", "Adverb"], answer: 2, difficulty: 2 },
    ],
  },
};
